import { useRef, useState } from 'react'
import CalculationPage from '../everyday-calculations/CalculationPage'
import { useToolResult } from '../../components/tools/useToolResult'
import { ASPECT_PRESETS, aspectSummary, calculateAspect } from './aspect'
import type { AspectAxis, AspectResult, AspectRounding } from './aspect'
const initial = () => ({ width: '1920', height: '1080', axis: 'width' as AspectAxis, target: '1280', rounding: 'round' as AspectRounding })
export default function AspectRatio() {
  const [values, setValues] = useState(initial)
  const [calculated, setCalculated] = useState<AspectResult | null>(null)
  const widthRef = useRef<HTMLInputElement>(null)
  const result = useToolResult()
  const clearResult = () => { setCalculated(null); result.reset() }
  const update = (patch: Partial<ReturnType<typeof initial>>) => { setValues(current => ({ ...current, ...patch })); clearResult() }
  const described = `aspect-help${result.error ? ' calculation-error' : ''}`
  return <CalculationPage title="縦横比・サイズ計算" description="幅と高さの比率を約分し、同じ比率の新しい寸法を計算します。" result={result} onReset={() => { setValues(initial()); clearResult(); widthRef.current?.focus() }} related={['image-resizer', 'unit-converter', 'percentage-calculator']} usage={<><p>元の幅と高さを入力して「計算する」を押します。新しい寸法を空欄にすると比率だけを表示します。プリセットは元の幅・高さに比の数字を入れます。縦横入替も元の幅・高さだけを交換し、新しく指定する側と値は維持します。</p><p>幅・高さは同じ単位で指定してください（例：両方px、両方mm）。画像ファイルは不要です。dpiや印刷の実寸へ換算する機能ではありません。端末・印刷機による表示や仕上がりの実寸は保証しません。</p><p>0より大きく1,000,000以下、小数6桁まで。全角数字も使えます。カンマ、指数表記、分数は使えません。入力した有限小数を整数化し、最大公約数で約分します。浮動小数の誤差で比の数字が増えることはありませんが、元の小数が細かい場合は正しい整数比も大きくなります。</p><p>指定した新しい寸法を固定し、計算する側だけを丸めます。整数への四捨五入は0.5を切り上げ、切り上げ・切り捨ても選べます。丸めで比率が変わる場合は表示寸法の比率を併記します。小数表示は6桁の目安で、循環小数などに「約」、微小な値に「0.000001未満」を付けます。入力を編集すると前の結果とコピー通知が消えます。</p></>}>
    <form onSubmit={event => { event.preventDefault(); setCalculated(null); void result.run(() => { const next = calculateAspect(values.width, values.height, values.axis, values.target, values.rounding); setCalculated(next); return aspectSummary(next) }) }}>
      <div className="everyday-columns"><label className="field-label" htmlFor="aspect-width">元の幅<input ref={widthRef} id="aspect-width" type="text" inputMode="decimal" maxLength={32} aria-describedby={described} value={values.width} onChange={event => update({ width: event.target.value })} /></label><label className="field-label" htmlFor="aspect-height">元の高さ<input id="aspect-height" type="text" inputMode="decimal" maxLength={32} aria-describedby={described} value={values.height} onChange={event => update({ height: event.target.value })} /></label></div>
      <div className="action-row aspect-presets" role="group" aria-label="元の比率のプリセット">{ASPECT_PRESETS.map(([width, height]) => <button key={`${width}:${height}`} type="button" className={`secondary-button ${values.width === width && values.height === height ? 'is-selected' : ''}`} aria-pressed={values.width === width && values.height === height} onClick={() => update({ width, height })}>{width}:{height}</button>)}<button id="aspect-swap" type="button" className="secondary-button" onClick={() => { setValues(current => ({ ...current, width: current.height, height: current.width })); clearResult() }}>縦横を入れ替える</button></div>
      <div className="everyday-columns"><label className="field-label" htmlFor="aspect-axis">新しく指定する側<select id="aspect-axis" aria-describedby={described} value={values.axis} onChange={event => update({ axis: event.target.value as AspectAxis })}><option value="width">幅</option><option value="height">高さ</option></select></label><label className="field-label" htmlFor="aspect-target">新しい{values.axis === 'width' ? '幅' : '高さ'}（任意）<input id="aspect-target" type="text" inputMode="decimal" maxLength={32} aria-describedby={described} value={values.target} onChange={event => update({ target: event.target.value })} /></label></div>
      <label className="field-label" htmlFor="aspect-rounding">計算する側の丸め<select id="aspect-rounding" aria-describedby={described} value={values.rounding} onChange={event => update({ rounding: event.target.value as AspectRounding })}><option value="round">整数に四捨五入</option><option value="ceil">整数に切り上げ</option><option value="floor">整数に切り捨て</option><option value="decimal">小数6桁の目安</option></select></label>
      <p className="calculation-help" id="aspect-help">同じ単位で入力してください。小数6桁・1,000,000以下、0は不可。新しい寸法が空欄なら比率だけを表示します。丸めるのは計算する側だけです。</p>
      <button id="aspect-calculate" type="submit" className="primary-button" disabled={result.busy}>計算する</button>
    </form>
    {calculated && <section className="calculation-result aspect-result" aria-labelledby="aspect-result-title"><h2 id="aspect-result-title">計算結果</h2><dl><div><dt>元の比率（幅:高さ）</dt><dd id="aspect-ratio">{calculated.original.ratio}</dd></div>{calculated.size && <><div><dt>新しい寸法（幅 × 高さ）</dt><dd id="aspect-size">{calculated.size.width} × {calculated.size.height}</dd></div><div><dt>丸め前の{values.axis === 'width' ? '高さ' : '幅'}（目安）</dt><dd>{calculated.size.idealOther}</dd></div>{calculated.size.ratioAfter && <div><dt>表示寸法の比率</dt><dd>{calculated.size.ratioAfter}</dd></div>}</>}</dl>{calculated.size && <p id="aspect-rounding-note" className="calculation-help">{calculated.size.rounding === 'decimal' ? '小数は表示上の目安です。内部では元の比率を維持して計算しています。' : calculated.size.changed ? '整数への丸めにより、元の比率と差があります。指定した寸法はそのまま維持しています。' : '元の比率を維持しています。'}</p>}</section>}
  </CalculationPage>
}
