import assert from 'node:assert/strict'
import test from 'node:test'
import {readFileSync} from 'node:fs'
import {defaultCatalogue,readCatalogue,catalogueReturnState,catalogueHomeState,canReturnToCatalogue} from '../src/state/catalogueState.ts'
test('一覧状態: 検索文字列・全カテゴリ・全棚を履歴と戻り先の間で保持',()=>{for(const category of ['all','developer','text','datetime','network','general','other'])for(const collection of ['all','favorites','recent']){const value={version:1,query:' ＱＲ 🍵 <画像> ',category,collection};assert.deepEqual(readCatalogue({catalogue:value}),value);assert.deepEqual(catalogueHomeState(catalogueReturnState(value)),{catalogue:value})}})
test('一覧状態: 未指定・未知バージョン・不正stateを既定へ戻し、不正フィールドだけ無効化',()=>{for(const state of [undefined,null,[],42,'bad',{catalogue:[]},{catalogue:{version:2}},{catalogueReturn:{version:1,query:'old'}}])assert.deepEqual(readCatalogue(state),defaultCatalogue());for(const state of [undefined,null,[],{catalogue:{version:1}},{catalogueReturn:{version:2}}])assert.equal(catalogueHomeState(state),undefined);assert.deepEqual(readCatalogue({catalogue:{version:1,query:9,category:'__proto__',collection:'future',extra:'drop'}}),defaultCatalogue());assert.deepEqual(readCatalogue({catalogue:{version:1,query:'画像',category:'deleted-category',collection:'recent',extra:'drop'}}),{version:1,query:'画像',category:'all',collection:'recent'})})
test('一覧状態: 保存内容は一覧条件だけで元のstateを変更しない',()=>{const original=Object.freeze({version:1,query:'秘密検索',category:'general',collection:'favorites',file:'private.png',input:'do not save'});const parsed=readCatalogue({catalogue:original});assert.deepEqual(Object.keys(parsed),['version','query','category','collection']);assert.equal(original.file,'private.png');const source=readFileSync(new URL('../src/state/catalogueState.ts',import.meta.url),'utf8')+readFileSync(new URL('../src/pages/HomePage.tsx',import.meta.url),'utf8');assert.ok(!/localStorage|sessionStorage|URLSearchParams|fetch\s*\(|sendBeacon/.test(source));assert.ok(source.includes('replace: true'))})

test('一覧状態: 直前の元一覧だけにBackを許し、不正・離れた履歴では使わない',()=>{const state={catalogueReturn:defaultCatalogue(),catalogueOriginIndex:3};assert.equal(canReturnToCatalogue(state,4),true);for(const index of [undefined,3,5,NaN])assert.equal(canReturnToCatalogue(state,index),false);for(const bad of [-1,Infinity,'3',null])assert.equal(canReturnToCatalogue({...state,catalogueOriginIndex:bad},4),false);assert.equal(canReturnToCatalogue({catalogueOriginIndex:3},4),false)})
