import assert from 'node:assert/strict'
import {tools} from '../src/tools/registry.ts'
import {navigate,evaluate,send,input,click,wait,viewport,assertNoOverflow,screenshot,finish,requests} from './browser-client.mjs'
const root=(process.env.TEST_SCREENSHOT_DIR||process.env.TEMP||'.').replaceAll('\\','/')+'/'
async function poll(expr){for(let i=0;i<150;i++){if(await evaluate(expr))return;await wait(40)}throw Error('timeout '+expr)}
const view=()=>evaluate(`({query:document.querySelector('#tool-search').value,category:document.querySelector('.category-filter[aria-pressed=true]').textContent,shelf:document.querySelector('.collection-button[aria-pressed=true]').textContent.replace(/^[^すお最]+|[0-9]+$/g,''),ids:[...document.querySelectorAll('.tool-card')].map(e=>e.dataset.toolId)})`)
async function nativeOpen(selector){await evaluate(`document.querySelector(${JSON.stringify(selector)}).focus()`);await send('Input.dispatchKeyEvent',{type:'keyDown',key:'Enter',code:'Enter',windowsVirtualKeyCode:13,text:'\r'});await send('Input.dispatchKeyEvent',{type:'keyUp',key:'Enter',code:'Enter',windowsVirtualKeyCode:13});await poll(`!!document.querySelector('.tool-header')`);await wait(100)}
async function back(){await evaluate('history.back()');await poll(`!!document.querySelector('#tool-search')`);await wait(100)}
async function forward(){await evaluate('history.forward()');await poll(`!!document.querySelector('.tool-header')`);await wait(100)}
async function choose(category){await evaluate(`(()=>{const b=[...document.querySelectorAll('.category-filter')].find(e=>e.textContent===${JSON.stringify(category)});b.click()})()`);await wait(100)}
async function matches(query,category,shelf){const v=await view();assert.equal(v.query,query);assert.equal(v.category,category);assert.ok(v.shelf.includes(shelf),v.shelf);return v}
await send('Emulation.setFocusEmulationEnabled',{enabled:true});await send('Page.bringToFront');await viewport(1280);await navigate('/');await evaluate(`localStorage.clear();history.replaceState({...history.state,usr:null},'',location.href)`);await navigate('/')
// Every tool, with a query that selects itself, its category, and recent/favorites return context.
let checked=0
for(const tool of tools){await navigate('/');await input('#tool-search',tool.name);await choose(({developer:'開発',text:'テキスト・変換',datetime:'日時',network:'ネットワーク',general:'一般',other:'その他'})[tool.category]);const before=await view();await nativeOpen(`.tool-card[data-tool-id="${tool.id}"] a`);await back();assert.deepEqual((await view()).ids,before.ids);assert.equal((await view()).query,tool.name);await forward();await click('.tool-navigation a');assert.deepEqual(await view(),before);checked++}
console.log('PASS: '+checked+' tools: combined query/category → Back/Forward/list link')
await navigate('/');await input('#tool-search','画像');await choose('一般');const historyBefore=await evaluate('history.length');await input('#tool-search','画像 回転');assert.equal(await evaluate('history.length'),historyBefore);await evaluate('window.scrollTo(0,500)');await wait(100);const scroll=await evaluate('scrollY');await input('#tool-search','画像');assert.equal(await evaluate('scrollY'),scroll)
for(const id of ['image-rotate','image-resizer','image-joiner']){const button=`.tool-card[data-tool-id="${id}"] .favorite-button`;if(await evaluate(`document.querySelector(${JSON.stringify(button)}).getAttribute('aria-pressed')`)!=='true')await click(button)}
await click('.collection-button:nth-child(2)');await matches('画像','一般','お気に入り');await click('.tool-card[data-tool-id="image-rotate"] a');await click('.detail-favorite');await back();let v=await matches('画像','一般','お気に入り');assert.ok(!v.ids.includes('image-rotate'));assert.ok(v.ids.includes('image-resizer'));await forward();await click('.tool-navigation a');await matches('画像','一般','お気に入り')
// New home entry is independent: editing it must not overwrite the old history entry.
await click('.search-clear');await choose('すべて');await click('.collection-button:nth-child(3)');await click('.tool-card a');await back();await matches('','すべて','最近使った道具');await forward();await click('.brand-link');await matches('','すべて','最近使った道具')
await click('.text-button');v=await matches('','すべて','最近使った道具');assert.deepEqual(v.ids,[]);await click('.empty-recovery button');v=await matches('','すべて','すべての道具');assert.equal(v.ids.length, 39)
// Empty-result clear/category reset is atomic and remains cleared on subsequent return.
await input('#tool-search','missing-private-catalogue-marker');await choose('ネットワーク');await click('.empty-recovery button:nth-child(1)');await matches('','ネットワーク','すべての道具');await input('#tool-search','missing-private-catalogue-marker');await click('.empty-recovery button:nth-child(2)');await matches('missing-private-catalogue-marker','すべて','すべての道具');await click('.empty-recovery button:last-child');await click('.tool-card[data-tool-id="image-rotate"] a');await back();await matches('','すべて','すべての道具')
// After Back/edit/Forward the explicit home link must use the latest origin entry.
await input('#tool-search','画像');await click('.tool-card[data-tool-id="image-rotate"] a');await back();await input('#tool-search','JSON');await forward();await click('.tool-navigation a');await matches('JSON','すべて','すべての道具')
await evaluate(`document.querySelector('.theme-option:first-child').focus()`);await send('Input.dispatchKeyEvent',{type:'keyDown',key:' ',code:'Space',windowsVirtualKeyCode:32,text:' '});await send('Input.dispatchKeyEvent',{type:'keyUp',key:' ',code:'Space',windowsVirtualKeyCode:32});assert.equal(await evaluate('navigator.userActivation.hasBeenActive'),true)
// Native same-URL history entries: each keeps its own filters without a shared cache.
await input('#tool-search','画像');await evaluate(`history.pushState({usr:null,key:'catalogue-independent-entry',idx:history.state.idx+1},'',location.href);dispatchEvent(new PopStateEvent('popstate'))`);await wait(150);await input('#tool-search','JSON');await click('.tool-card[data-tool-id="json-formatter"] a');await back();await matches('JSON','すべて','すべての道具');await evaluate('history.back()');await poll(`!!document.querySelector('#tool-search')&&document.querySelector('#tool-search').value==='画像'`);await matches('画像','すべて','すべての道具');await evaluate('history.forward()');await poll(`!!document.querySelector('#tool-search')&&document.querySelector('#tool-search').value==='JSON'`);await matches('JSON','すべて','すべての道具');await click('.search-clear');await input('#tool-search','画像')
// Tool content is never retained, even though catalogue filters are.
await click('.tool-card[data-tool-id="image-rotate"] a');await click('.tool-navigation a');await click('.search-clear');await input('#tool-search','文字数');await click('.tool-card[data-tool-id="character-counter"] a');await input('textarea','private-tool-content');await back();await matches('文字数','すべて','すべての道具');await forward();assert.equal(await evaluate('document.querySelector("textarea").value'),'')
await navigate('/tools/json-formatter');await click('.tool-navigation a');await matches('','すべて','すべての道具');await input('#tool-search','画像');await navigate('/tools/not-real');await click('.not-found-panel a');await matches('','すべて','すべての道具')
// A blocked lazy chunk keeps the filtered catalogue available through the error link.
await input('#tool-search','QR');await send('Network.setBlockedURLs',{urls:['*QrCodeGenerator-*.js']});await send('Page.reload');await poll(`!!document.querySelector('#tool-search')`);await click('.tool-card[data-tool-id="qr-code-generator"] a');await poll(`!!document.querySelector('#tool-load-title')`);await click('.error-box + .action-row a');await matches('QR','すべて','すべての道具');await send('Network.setBlockedURLs',{urls:[]});await click('.search-clear')
// Invalid and old schema states arrive through Router's history payload on document reload.
await evaluate(`history.replaceState({...history.state,usr:{catalogue:{version:1,query:'画像',category:'removed',collection:'recent'}}},'',location.href)`);await send('Page.reload');await poll(`!!document.querySelector('#tool-search')`);await matches('画像','すべて','最近使った道具');await evaluate(`history.replaceState({...history.state,usr:{catalogue:{version:99,query:'bad',category:'general',collection:'favorites'}}},'',location.href)`);await send('Page.reload');await poll(`!!document.querySelector('#tool-search')`);await matches('','すべて','すべての道具')
// Real new tab: no state/URL query is transferred by an ordinary tool link.
await input('#tool-search','画像');const base=await evaluate('location.origin');const newTab=await send('Target.createTarget',{url:base+'/tools/image-rotate'});const targets=await(await fetch('http://127.0.0.1:9222/json')).json();const target=targets.find(t=>t.id===newTab.targetId);const ws=new WebSocket(target.webSocketDebuggerUrl);await new Promise(r=>ws.addEventListener('open',r,{once:true}));let n=0;const pending=new Map();ws.addEventListener('message',e=>{const m=JSON.parse(e.data);if(m.id){pending.get(m.id)?.(m.result);pending.delete(m.id)}});const tabEval=expr=>new Promise(r=>{const id=++n;pending.set(id,v=>r(v.result?.value));ws.send(JSON.stringify({id,method:'Runtime.evaluate',params:{expression:expr,returnByValue:true}}))});for(let i=0;i<100;i++){if(await tabEval(`!!document.querySelector('.tool-navigation a')`))break;await wait(50)}await tabEval(`document.querySelector('.tool-navigation a').click()`);for(let i=0;i<100;i++){if(await tabEval(`!!document.querySelector('#tool-search')`))break;await wait(50)}assert.equal(await tabEval(`document.querySelector('#tool-search').value`),'');assert.equal(await tabEval(`document.querySelectorAll('.tool-card').length`), 39);ws.close();await send('Target.closeTarget',{targetId:newTab.targetId});await send('Page.bringToFront')
for(const theme of ['light','dark'])for(const width of [1280,320]){await viewport(width);await navigate('/');await click(theme==='light'?'.theme-option:first-child':'.theme-option:last-child');await input('#tool-search','画像');await choose('一般');await click('.collection-button:nth-child(3)');const expected=await view();await evaluate(`document.querySelector('.tool-card a').focus()`);await send('Input.dispatchKeyEvent',{type:'keyDown',key:'Enter',code:'Enter',windowsVirtualKeyCode:13,text:'\r'});await send('Input.dispatchKeyEvent',{type:'keyUp',key:'Enter',code:'Enter',windowsVirtualKeyCode:13});await poll(`!!document.querySelector('.tool-header')`);await evaluate(`document.querySelector('.tool-navigation a').focus()`);await send('Input.dispatchKeyEvent',{type:'keyDown',key:'Enter',code:'Enter',windowsVirtualKeyCode:13,text:'\r'});await send('Input.dispatchKeyEvent',{type:'keyUp',key:'Enter',code:'Enter',windowsVirtualKeyCode:13});await poll(`!!document.querySelector('#tool-search')`);assert.deepEqual(await view(),expected);await assertNoOverflow();await evaluate(`document.querySelector('#tool-search').scrollIntoView({block:'center',behavior:'instant'})`);await screenshot(root+'catalogue-'+theme+'-'+width+'.png')}
assert.equal(await evaluate(`JSON.stringify(localStorage).includes('private-tool-content')||JSON.stringify(localStorage).includes('missing-private-catalogue-marker')||location.search!==''`),false);assert.equal(requests.some(r=>(r.url+r.body).includes('missing-private-catalogue-marker')||(r.url+r.body).includes('private-tool-content')),false);finish();console.log('PASS: query/category/shelf; independent entries; no history growth or filter scroll jump; clear/reset; latest favorite/recent; default direct/unknown/new-tab/invalid state; tool inputs empty; light/dark320 keyboard; no URL/storage inputs')
