import assert from 'node:assert/strict'
import { navigate, evaluate, send, input, click, viewport, screenshot, wait, assertNoOverflow, finish } from './browser-client.mjs'

const origin = new URL(process.env.TEST_BASE_URL || 'http://127.0.0.1:5173').origin
const outputPrefix=(process.env.TEST_SCREENSHOT_DIR || process.env.TEMP || '.').replaceAll('\\','/')+'/poketsuru-calculations-'
const select = async (selector,value) => { await evaluate(`(()=>{const el=document.querySelector(${JSON.stringify(selector)});el.value=${JSON.stringify(value)};el.dispatchEvent(new Event('change',{bubbles:true}))})()`);await wait(100) }
const key = async (name,code) => { await send('Input.dispatchKeyEvent',{type:'keyDown',key:name,code:name,windowsVirtualKeyCode:code,...(name==='Enter'?{text:'\r'}:{})});await send('Input.dispatchKeyEvent',{type:'keyUp',key:name,code:name,windowsVirtualKeyCode:code});await wait(120) }
const absent = async () => { assert.equal(await evaluate('!!document.querySelector(".calculation-result")'),false);assert.equal(await evaluate('document.querySelector("#calculation-copy").disabled'),true) }
const error = async text => assert.ok((await evaluate('document.querySelector("[role=alert]")?.textContent||""')).includes(text),text)
const copy = async expected => { await click('#calculation-copy');assert.ok((await evaluate('navigator.clipboard.readText()')).includes(expected));assert.ok(await evaluate('document.querySelector(".calculation-status").textContent.includes("コピーしました")')) }
const theme = async value => { await click(value==='light'?'.theme-option:first-child':'.theme-option:last-child');await wait(300) }
const capture = async name => { await assertNoOverflow();await screenshot(outputPrefix+name+'.png') }
const fillProduct = async (id,p,a,u='g',n='') => { await input(`#product-price-${id}`,p);await input(`#product-amount-${id}`,a);await select(`#product-unit-${id}`,u);await input(`#product-name-${id}`,n) }
const fillIngredient = async (id,n,a,u='') => { await input(`#ingredient-name-${id}`,n);await input(`#ingredient-amount-${id}`,a);await input(`#ingredient-unit-${id}`,u) }

await send('Emulation.setFocusEmulationEnabled',{enabled:true});await send('Page.bringToFront');await send('Browser.grantPermissions',{permissions:['clipboardReadWrite','clipboardSanitizedWrite'],origin})
await viewport(1280);await navigate('/');await evaluate('localStorage.clear()');await navigate('/')
assert.equal(await evaluate('document.querySelectorAll(".tool-card").length'),25)
for(const [query,id] of [['どっちが安い','unit-price-comparison'],['何人分','recipe-scaler']]){await input('#tool-search',query);assert.ok(await evaluate(`!!document.querySelector('.tool-card[data-tool-id="${id}"]')`));await input('#tool-search','')}
await navigate('/tools/unit-price-comparison');await theme('light');await absent();await click('#price-calculate');await error('数値')
await fillProduct(1,'２９８','５００','g','比較A');await fillProduct(2,'500','1','kg','比較B');await click('#price-calculate')
assert.ok(await evaluate('document.querySelector(".price-results").textContent.includes("59.6円")'));assert.ok(await evaluate('document.querySelector(".price-results li:last-child").textContent.includes("最安")'));await copy('比較B：50円 / 最安')
await capture('price-light-desktop-input');await evaluate(`document.querySelector(".calculation-result").scrollIntoView({behavior:"instant",block:"start"})`);await capture('price-light-desktop-result')
await input('#product-price-2','596');await absent();await click('#price-calculate');assert.equal(await evaluate('[...document.querySelectorAll(".price-result-value span")].filter(el=>el.textContent==="最安（同値）").length'),2)
await select('#product-unit-2','L');await absent();await click('#price-calculate');await error('別々')
await select('#product-unit-1','mL');await click('#price-calculate');assert.ok(await evaluate('document.querySelector("#price-result-title").textContent.includes("100mL")'))
await select('#price-basis','large');await absent();await click('#price-calculate');assert.ok(await evaluate('document.querySelector("#price-result-title").textContent.includes("1000mL")'))
await input('#product-amount-1','0');await click('#price-calculate');await error('0より');await input('#product-amount-1','500');await input('#product-price-1','0');await click('#price-calculate');assert.ok(await evaluate('document.querySelector(".price-results li:first-child").textContent.includes("0円最安")'))
await click('#product-add');assert.equal(await evaluate('document.activeElement.id'),'product-name-3');await fillProduct(3,'900','2','L','比較C');await click('#product-add');assert.equal(await evaluate('document.activeElement.id'),'product-name-4');assert.equal(await evaluate('document.querySelector("#product-add").disabled'),true);await fillProduct(4,'1000','3','L','比較D');await click('#price-calculate');assert.equal(await evaluate('document.querySelectorAll(".price-results li").length'),4)
await click('.product-row:nth-child(3) .row-remove');assert.equal(await evaluate('document.activeElement.id'),'product-name-4');await absent();await click('#price-calculate');assert.equal(await evaluate('document.querySelectorAll(".price-results li").length'),3)
await click('#calculation-reset');await absent();assert.equal(await evaluate('document.querySelectorAll(".product-row").length'),2);assert.equal(await evaluate('document.querySelector("#product-price-1").value'),'')
await fillProduct(1,'100','2','個','商品A');await fillProduct(2,'240','6','個','商品B');await evaluate('document.querySelector("#price-calculate").focus()');await key('Enter',13);assert.ok(await evaluate('document.querySelector("#price-result-title").textContent.includes("1個")'))
await key('Tab',9);assert.equal(await evaluate('document.activeElement.id'),'calculation-copy');assert.ok(await evaluate('getComputedStyle(document.activeElement).outlineStyle!=="none"'))
for(const t of ['light','dark']){await theme(t);await viewport(320);await evaluate('window.scrollTo({top:0,behavior:"instant"})');await capture(`price-${t}-mobile-input`);await evaluate(`document.querySelector(".calculation-result").scrollIntoView({behavior:"instant",block:"start"})`);await capture(`price-${t}-mobile-result`)}
await viewport(1280);await theme('dark');await evaluate('document.querySelector(".calculation-result").scrollIntoView({behavior:"instant",block:"start"})');await capture('price-dark-desktop-result')
await click('.detail-favorite');await send('Page.reload');await wait(600);assert.equal(await evaluate('document.querySelector(".detail-favorite").getAttribute("aria-pressed")'),'true');assert.equal(await evaluate('document.querySelector("#product-price-1").value'),'')
assert.equal(await evaluate('JSON.parse(localStorage.getItem("poketsuru-tool-shelf-v1")).recent[0]'),'unit-price-comparison')

await navigate('/tools/recipe-scaler');await theme('light');await absent();await click('#recipe-calculate');await error('名前')
await fillIngredient(1,'卵','１','個');await click('#ingredient-add');assert.equal(await evaluate('document.activeElement.id'),'ingredient-name-2');await fillIngredient(2,'小麦粉','100.5','g');await click('#ingredient-add');await fillIngredient(3,'塩','適量');await click('#ingredient-add');await fillIngredient(4,'胡椒','少々');await click('#recipe-calculate')
assert.deepEqual(await evaluate('[...document.querySelectorAll(".recipe-results dd")].map(el=>el.textContent)'),['1.5 個','150.75 g','適量','少々']);await copy('卵：1.5 個')
await evaluate('window.scrollTo({top:0,behavior:"instant"})');await capture('recipe-light-desktop-input');await evaluate(`document.querySelector(".calculation-result").scrollIntoView({behavior:"instant",block:"start"})`);await capture('recipe-light-desktop-result')
await input('#recipe-target','4');await absent();await click('#recipe-calculate');assert.equal(await evaluate('document.querySelector(".recipe-results dd").textContent'),'2 個')
await input('#recipe-original','0');await click('#recipe-calculate');await error('0より');await input('#recipe-original','2')
await click('#recipe-mode-factor');await absent();await input('#recipe-factor','0.5');await click('#recipe-calculate');assert.equal(await evaluate('document.querySelector(".recipe-results dd").textContent'),'0.5 個')
await input('#ingredient-amount-1','1.005');await input('#recipe-factor','1');await select('#recipe-places','2');await click('#recipe-calculate');assert.equal(await evaluate('document.querySelector(".recipe-results dd").textContent'),'1.01 個')
await select('#recipe-places','3');await input('#ingredient-amount-1','0.000001');await click('#recipe-calculate');assert.equal(await evaluate('document.querySelector(".recipe-results dd").textContent'),'0.001未満 個')
await input('#ingredient-amount-1','1/2');await click('#recipe-calculate');await error('分数');await input('#ingredient-amount-1','1');await input('#recipe-factor','1.5');await click('#recipe-calculate');await copy('胡椒：少々')
for(const t of ['light','dark']){await theme(t);await viewport(320);await evaluate('window.scrollTo({top:0,behavior:"instant"})');await capture(`recipe-${t}-mobile-input`);await evaluate(`document.querySelector(".calculation-result").scrollIntoView({behavior:"instant",block:"start"})`);await capture(`recipe-${t}-mobile-result`)}
await viewport(1280);await theme('dark');await evaluate('document.querySelector(".calculation-result").scrollIntoView({behavior:"instant",block:"start"})');await capture('recipe-dark-desktop-result')
await click('.ingredient-row:nth-child(2) .row-remove');assert.equal(await evaluate('document.activeElement.id'),'ingredient-name-3');await absent();await click('#recipe-calculate');assert.equal(await evaluate('document.querySelectorAll(".recipe-results dd").length'),3)
for(let i=3;i<20;i++)await click('#ingredient-add');assert.equal(await evaluate('document.querySelectorAll(".ingredient-row").length'),20);assert.equal(await evaluate('document.querySelector("#ingredient-add").disabled'),true)
await evaluate(`(()=>{for(const [i,row] of [...document.querySelectorAll('.ingredient-row')].entries()){for(const [suffix,value] of [['name','材料'+i],['amount','1'],['unit','g']]){const el=row.querySelector('[id^=ingredient-'+suffix+']');Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(el,value);el.dispatchEvent(new Event('input',{bubbles:true}))}}})()`);await click('#recipe-calculate');assert.equal(await evaluate('document.querySelectorAll(".recipe-results dd").length'),20)
await click('#calculation-reset');await absent();assert.equal(await evaluate('document.querySelectorAll(".ingredient-row").length'),1);assert.equal(await evaluate('document.querySelector("#recipe-original").value'),'2')
await evaluate('document.querySelector("#ingredient-name-1").focus()');await key('Tab',9);assert.equal(await evaluate('document.activeElement.id'),'ingredient-amount-1')
await click('.detail-favorite');await send('Page.reload');await wait(600);assert.equal(await evaluate('document.querySelector(".detail-favorite").getAttribute("aria-pressed")'),'true');assert.equal(await evaluate('document.querySelector("#ingredient-name-1").value'),'')
const storage=await evaluate('Object.fromEntries(Object.keys(localStorage).map(key=>[key,localStorage.getItem(key)]))');assert.deepEqual(Object.keys(storage).sort(),['poketsuru-theme','poketsuru-tool-shelf-v1']);const shelf=JSON.parse(storage['poketsuru-tool-shelf-v1']);assert.ok(shelf.favorites.includes('unit-price-comparison')&&shelf.favorites.includes('recipe-scaler'));assert.equal(shelf.recent[0],'recipe-scaler');assert.ok(!JSON.stringify(storage).includes('比較A'));assert.ok(!JSON.stringify(storage).includes('小麦粉'))
await navigate('/');await click('.collection-button:nth-child(2)');assert.equal(await evaluate('document.querySelectorAll(".tool-card").length'),2)
await navigate('/tools/recipe-scaler');assert.ok(await evaluate(`!!document.querySelector('.calculation-related a[href="/tools/unit-price-comparison"]')`))
await navigate('/tools/unit-price-comparison');await viewport(320);await fillProduct(1,'1000000000','0.000001','g','A'.repeat(80));await fillProduct(2,'1000000000','1000000000','g','B'.repeat(80));await click('#price-calculate');await assertNoOverflow();await evaluate('document.querySelector(".calculation-result").scrollIntoView({behavior:"instant",block:"start"})');await capture('price-extreme-mobile');
await navigate('/tools/recipe-scaler');await fillIngredient(1,'C'.repeat(80),'1000000000','u'.repeat(20));await click('#recipe-calculate');await assertNoOverflow();
await send('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'reduce'}]});assert.equal(await evaluate('getComputedStyle(document.documentElement).scrollBehavior'),'auto')
finish();console.log('PASS: price/recipe calculations, add/delete limits, update/reset, native keyboard/focus, real clipboard, shelf persistence, privacy, themes and 320px')
