import assert from 'node:assert/strict'
import {navigate,evaluate,send,input,click,viewport,wait,screenshot,assertNoOverflow,finish} from './browser-client.mjs'
const root=(process.env.TEST_SCREENSHOT_DIR||process.env.TEMP||'.').replaceAll('\\','/')+'/'
const origin=process.env.TEST_BASE_URL||'http://127.0.0.1:5173'
const key=async(key,code,text,modifiers)=>{await send('Input.dispatchKeyEvent',{type:'keyDown',key,code:key,windowsVirtualKeyCode:code,...(text?{text}:{}),...(modifiers?{modifiers}:{})});await send('Input.dispatchKeyEvent',{type:'keyUp',key,code:key,windowsVirtualKeyCode:code,...(modifiers?{modifiers}:{})});await wait(150)}
const clear=async()=>{assert.equal(await evaluate('!!document.querySelector(".grouping-result")'),false);assert.equal(await evaluate('document.querySelector("#grouping-copy").disabled'),true);assert.equal(await evaluate('document.querySelector(".grouping-status").textContent'),'')}
const valid=async(n,k,sizes)=>{
 const data=await evaluate(`({groups:[...document.querySelectorAll('.grouping-group')].map(el=>el.querySelectorAll('[data-candidate-id]').length),ids:[...document.querySelectorAll('[data-candidate-id]')].map(el=>Number(el.dataset.candidateId)),status:document.querySelector('.grouping-status').textContent})`)
 assert.equal(data.groups.length,k);assert.equal(data.ids.length,n);assert.equal(new Set(data.ids).size,n);assert.deepEqual([...data.ids].sort((a,b)=>a-b),Array.from({length:n},(_,i)=>i+1));assert.ok(Math.max(...data.groups)-Math.min(...data.groups)<=1);if(sizes)assert.deepEqual(data.groups,sizes);assert.ok(data.status.includes(n+'候補を'+k+'組'))
}
const copy=async()=>{await click('#grouping-copy');const value=(await evaluate('navigator.clipboard.readText()')).replace(/\r\n/g,'\n');assert.equal(value,await evaluate('document.querySelector("#grouping-output").value'));assert.equal(await evaluate('document.querySelector(".grouping-status").textContent'),'コピーしました');return value}
await send('Emulation.setFocusEmulationEnabled',{enabled:true});await send('Page.bringToFront');await send('Browser.grantPermissions',{permissions:['clipboardReadWrite','clipboardSanitizedWrite'],origin});await viewport(1280);await navigate('/tools/random-grouping')
assert.equal(await evaluate('document.title'),'ランダム組み分け | ぽけつる');await click('#grouping-draw');assert.ok(await evaluate('!!document.querySelector("#grouping-error")'));await clear()
await input('#grouping-candidates',' a \r\n\r\n b ');await click('#grouping-draw');await valid(2,2,[1,1]);const first=await copy();assert.ok(first.includes(': a'));assert.ok(first.includes(': b'))
await input('#grouping-count','1');await clear();await click('#grouping-draw');assert.ok(await evaluate('document.querySelector("#grouping-error").textContent.includes("組数は2〜2")'))
for(const value of ['3','0','2.5','bad','']){await input('#grouping-count',value);await click('#grouping-draw');await clear();assert.ok(await evaluate('!!document.querySelector("#grouping-error")'))}
await input('#grouping-count','２');await click('#grouping-draw');await valid(2,2)
// A deterministic API override proves redraw updates; restore real crypto afterwards.
await evaluate('window.groupingCrypto=crypto.getRandomValues.bind(crypto);crypto.getRandomValues=array=>{array.fill(0);return array}');await click('#grouping-draw');const zero=await evaluate('document.querySelector("#grouping-output").value');await evaluate('crypto.getRandomValues=array=>{array.fill(1);return array}');await click('#grouping-draw');assert.notEqual(await evaluate('document.querySelector("#grouping-output").value'),zero);await evaluate('crypto.getRandomValues=window.groupingCrypto')
await input('#grouping-candidates','りん\nりん\n<img src=x onerror="window.groupingXss=1">\n👩🏽‍💻');assert.ok(await evaluate('document.querySelector("#grouping-duplicates").textContent.includes("同名")'));await click('#grouping-draw');await valid(4,2,[2,2]);assert.equal(await evaluate('document.querySelectorAll(".grouping-members li > span:last-child").length'),4);assert.equal(await evaluate('[...document.querySelectorAll(".grouping-members li > span:last-child")].filter(el=>el.textContent==="りん").length'),2);assert.equal(await evaluate('!!document.querySelector(".grouping-result img")'),false);assert.equal(await evaluate('!!window.groupingXss'),false);assert.ok((await copy()).includes('<img src=x onerror="window.groupingXss=1">'))
const hundred=Array.from({length:100},(_,i)=>'参加者'+(i+1)).join('\n');await input('#grouping-candidates',hundred);await input('#grouping-count','3');await evaluate('window.groupingCryptoCalls=0;crypto.getRandomValues=array=>{window.groupingCryptoCalls++;return window.groupingCrypto(array)}');await click('#grouping-draw');await valid(100,3,[34,33,33]);assert.ok(await evaluate('window.groupingCryptoCalls>=99&&window.groupingCryptoCalls<=99*128'));await evaluate('crypto.getRandomValues=window.groupingCrypto');assert.equal((await copy()).match(/^候補\d+: /gm).length,100)
await input('#grouping-count','100');await click('#grouping-draw');await valid(100,100,Array(100).fill(1));await viewport(320);await assertNoOverflow()
await input('#grouping-candidates',hundred+'\n参加者101');await clear();await click('#grouping-draw');assert.ok(await evaluate('document.querySelector("#grouping-error").textContent.includes("2〜100")'))
await input('#grouping-candidates','😀'.repeat(101)+'\nb');await click('#grouping-draw');assert.ok(await evaluate('document.querySelector("#grouping-error").textContent.includes("100文字")'))
// Over-limit native paste is rejected, preserving the input rather than truncating it.
await input('#grouping-candidates','元の候補\n残す候補');await input('#grouping-count','2');await click('#grouping-draw');await evaluate('navigator.clipboard.writeText("x".repeat(30001))');await evaluate('document.querySelector("#grouping-candidates").focus();document.querySelector("#grouping-candidates").select()');await key('v',86,null,2);await wait(200);assert.equal(await evaluate('document.querySelector("#grouping-candidates").value'),'元の候補\n残す候補');await clear();assert.ok(await evaluate('document.querySelector("#grouping-error").textContent.includes("元の入力を保持")'))
await click('#grouping-reset');assert.equal(await evaluate('document.activeElement.id'),'grouping-candidates');assert.equal(await evaluate('document.querySelector("#grouping-candidates").value'),'');assert.equal(await evaluate('document.querySelector("#grouping-count").value'),'2');await clear()
await input('#grouping-candidates','one\ntwo\nthree');await evaluate('document.querySelector("#grouping-candidates").focus()');await key('Tab',9);assert.equal(await evaluate('document.activeElement.id'),'grouping-count');await key('Enter',13,'\r');await valid(3,2,[2,1]);const status=await evaluate('document.querySelector(".grouping-status").textContent');await evaluate('document.querySelector("#grouping-draw").focus()');await key(' ',32,' ');await valid(3,2);assert.notEqual(await evaluate('document.querySelector(".grouping-status").textContent'),status)
// Late copy completions cannot revive feedback after edit or redraw; latest copy wins.
await evaluate('window.groupingCopy=navigator.clipboard.writeText.bind(navigator.clipboard);window.pendingGroupCopies=[];navigator.clipboard.writeText=()=>new Promise((resolve,reject)=>window.pendingGroupCopies.push({resolve,reject}))');await click('#grouping-copy');await input('#grouping-count','3');await evaluate('window.pendingGroupCopies[0].resolve()');await wait(100);await clear();await click('#grouping-draw');await click('#grouping-copy');await click('#grouping-draw');await evaluate('window.pendingGroupCopies[1].resolve()');await wait(100);assert.equal(await evaluate('document.querySelector(".grouping-status").textContent.includes("コピーしました")'),false)
await click('#grouping-copy');await click('#grouping-copy');await evaluate('window.pendingGroupCopies[3].resolve()');await wait(100);await evaluate('window.pendingGroupCopies[2].reject(new Error("old"))');await wait(100);assert.equal(await evaluate('document.querySelector(".grouping-status").textContent'),'コピーしました');assert.equal(await evaluate('!!document.querySelector("#grouping-error")'),false);await evaluate('navigator.clipboard.writeText=window.groupingCopy')
await evaluate('crypto.getRandomValues=()=>{throw new Error("乱数の生成テスト") }');await click('#grouping-draw');await clear();assert.ok(await evaluate('!!document.querySelector("#grouping-error")'));await evaluate('crypto.getRandomValues=undefined');await click('#grouping-draw');assert.ok(await evaluate('document.querySelector("#grouping-error").textContent.includes("安全な組み分け")'));await evaluate('crypto.getRandomValues=window.groupingCrypto')
for(const theme of ['light','dark'])for(const width of [1280,320]){
 await viewport(width);await click(theme==='light'?'.theme-option:first-child':'.theme-option:last-child');await wait(600);await click('#grouping-reset');await input('#grouping-candidates','りん\nゆう\nそら\nあお\nりん\nさき\nはる');await input('#grouping-count','3');await click('#grouping-draw');await valid(7,3,[3,2,2]);await assertNoOverflow();await evaluate('window.scrollTo({top:0,behavior:"instant"})');await screenshot(root+'grouping-'+theme+'-'+width+'-input.png');await evaluate('document.querySelector(".grouping-result").scrollIntoView({block:"start",behavior:"instant"})');await screenshot(root+'grouping-'+theme+'-'+width+'-result.png');await copy()
}
await input('#grouping-candidates','😀'.repeat(100)+'\n'+'長い名前'.repeat(25));await input('#grouping-count','2');await click('#grouping-draw');await valid(2,2);await assertNoOverflow();await evaluate('document.querySelector(".grouping-result").scrollIntoView({block:"start",behavior:"instant"})');await screenshot(root+'grouping-long-mobile.png')
await send('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'reduce'}]});await click('#grouping-draw');await valid(2,2);assert.equal(await evaluate('getComputedStyle(document.querySelector(".grouping-group")).animationName'),'none');assert.equal(await evaluate('document.querySelector(".grouping-status").getAttribute("aria-live")'),'polite')
await input('#grouping-candidates',' 姓  名 \n別  名');await click('#grouping-draw');await valid(2,2);assert.equal(await evaluate('getComputedStyle(document.querySelector(".grouping-members li > span:last-child")).whiteSpace'),'pre-wrap');assert.ok((await copy()).includes(': 姓  名'));await assertNoOverflow()
if(!await evaluate('document.querySelector(".detail-favorite").getAttribute("aria-pressed")==="true"'))await click('.detail-favorite');assert.ok(await evaluate('JSON.parse(localStorage.getItem("poketsuru-tool-shelf-v1")).favorites.includes("random-grouping")'));assert.equal(await evaluate('JSON.parse(localStorage.getItem("poketsuru-tool-shelf-v1")).recent[0]'),'random-grouping')
await input('#grouping-candidates','非保存確認-甲\n非保存確認-乙');await click('#grouping-draw');assert.equal(await evaluate('Object.values(localStorage).some(value=>value.includes("非保存確認"))'),false);assert.equal(await evaluate('location.search'),'')
await click('.calculation-related a');assert.equal(await evaluate('document.title'),'ルーレット抽選 | ぽけつる');await click('#draw-roulette');assert.ok(await evaluate('!!document.querySelector(".roulette-result strong")'));await input('#roulette-candidates','one');assert.equal(await evaluate('!!document.querySelector(".roulette-result strong")'),false);await assertNoOverflow()
await navigate('/');await input('#tool-search','班分け');assert.ok(await evaluate('!!document.querySelector(\'.tool-card[data-tool-id="random-grouping"]\')'));await click('.tool-card[data-tool-id="random-grouping"] a');assert.equal(await evaluate('document.querySelector("#grouping-candidates").value'),'');await clear()
finish();console.log('PASS: grouping 2/100 candidates,balanced/all-single groups,duplicates/HTML/emoji/limits,native paste/Tab/Enter/Space,real crypto and clipboard,redraw/reset/edit and copy races,4 layouts/reduced motion,ID-only shelf/search/privacy and roulette regression')
