import assert from 'node:assert/strict'
import fs from 'node:fs/promises'
import path from 'node:path'
import {send,evaluate,wait,navigate,click,viewport,assertNoOverflow,screenshot,finish} from './browser-client.mjs'
const root=(process.env.TEST_SCREENSHOT_DIR||process.env.TEMP||'.').replaceAll('\\','/')+'/'
async function poll(expr){for(let i=0;i<300;i++){if(await evaluate(expr))return;await wait(30)}throw Error('timeout '+expr)}
async function ready(){await poll(`!!document.querySelector('#image-download')&&!document.querySelector('.tool-panel [role="status"]').textContent.includes('画像を確認')`)}
async function load(index){await evaluate(`(()=>{const d=new DataTransfer();d.items.add(window.rotateFixtures[${index}]);const e=document.querySelector('#image-files');e.files=d.files;e.dispatchEvent(new Event('change',{bubbles:true}))})()`)}
async function pixels(){return evaluate(`(async()=>{const blob=await(await fetch(document.querySelector('#image-download').href)).blob();const b=await createImageBitmap(blob);const c=document.createElement('canvas');c.width=b.width;c.height=b.height;const x=c.getContext('2d');x.drawImage(b,0,0);const result={width:b.width,height:b.height,data:[...x.getImageData(0,0,b.width,b.height).data]};b.close();c.width=0;c.height=0;return result})()`)}
function expected(src,operation){const {width:w,height:h,data}=src;let ow=w,oh=h;if(operation==='right'||operation==='left'){ow=h;oh=w}const out=Array(w*h*4).fill(0);for(let y=0;y<h;y++)for(let x=0;x<w;x++){let xx=x,yy=y;if(operation==='right'){xx=h-1-y;yy=x}else if(operation==='left'){xx=y;yy=w-1-x}else if(operation==='half'){xx=w-1-x;yy=h-1-y}else if(operation==='horizontal'){xx=w-1-x}else if(operation==='vertical'){yy=h-1-y}for(let k=0;k<4;k++)out[(yy*ow+xx)*4+k]=data[(y*w+x)*4+k]}return {width:ow,height:oh,data:out}}
async function fixtures(){await evaluate(`(async()=>{window.rotateFixtures=[];window.fixturePixels=[];const read=async blob=>{const b=await createImageBitmap(blob);const c=document.createElement('canvas');c.width=b.width;c.height=b.height;const x=c.getContext('2d');x.drawImage(b,0,0);const result={width:b.width,height:b.height,data:[...x.getImageData(0,0,b.width,b.height).data]};b.close();c.width=0;c.height=0;return result};window.readFixture=read;
 for(const [w,h,mime,name]of[[7,5,'image/png','private-asymmetric.png'],[8192,1,'image/png','wide.png'],[1,8192,'image/png','tall.png'],[64,40,'image/jpeg','base.jpg'],[7,5,'image/webp','still.webp'],[128,80,'image/png','letters.png']]){const c=document.createElement('canvas');c.width=w;c.height=h;const x=c.getContext('2d');for(let yy=0;yy<h;yy++)for(let xx=0;xx<w;xx++){x.fillStyle='rgb('+((xx*37+yy*19)%256)+','+((xx*11+yy*53)%256)+','+((xx*71+yy*7)%256)+')';x.fillRect(xx,yy,1,1)}if(mime!=='image/jpeg'){x.clearRect(0,0,1,1);x.clearRect(2,1,1,1);x.fillStyle='rgba(255,0,0,0.5)';x.fillRect(2,1,1,1)}if(w===128){x.fillStyle='white';x.fillRect(0,0,w,h);for(const[col,xx,yy]of[['#e33',0,0],['#1a5',80,0],['#25c',0,50],['#e9b500',80,50]]){x.fillStyle=col;x.fillRect(xx,yy,48,30)}x.fillStyle='black';x.fillRect(52,10,5,45);x.fillRect(52,10,25,5);x.fillRect(52,30,20,5)}const b=await new Promise(r=>c.toBlob(r,mime,1));window.rotateFixtures.push(new File([b],name,{type:mime}));window.fixturePixels.push(await read(b));c.width=0;c.height=0}
 const jpeg=new Uint8Array(await window.rotateFixtures[3].arrayBuffer());for(let orientation=1;orientation<=8;orientation++){const p=new Uint8Array(32),v=new DataView(p.buffer);p.set([69,120,105,102,0,0,73,73]);v.setUint16(8,42,true);v.setUint32(10,8,true);v.setUint16(14,1,true);v.setUint16(16,0x112,true);v.setUint16(18,3,true);v.setUint32(20,1,true);v.setUint16(24,orientation,true);const b=new Blob([jpeg.subarray(0,2),new Uint8Array([255,225,0,34]),p,jpeg.subarray(2)],{type:'image/jpeg'});window.rotateFixtures.push(new File([b],'exif-'+orientation+'.jpg',{type:'image/jpeg'}))}
})()`)}
await send('Emulation.setFocusEmulationEnabled',{enabled:true});await send('Page.bringToFront');await viewport(1280);await navigate('/tools/image-rotate');await fixtures()
for(const id of ['left','right','half','horizontal','vertical','original'])assert.equal(await evaluate(`document.querySelector('#rotate-${id}').disabled`),true)
await load(0);await ready();const source=await evaluate('window.fixturePixels[0]');assert.deepEqual(await pixels(),source)
let result=source;for(const op of ['right','right','right','right','horizontal','horizontal','vertical','vertical','half','half','left','horizontal','right','vertical']){await click('#rotate-'+op);await ready();result=expected(result,op);assert.deepEqual(await pixels(),result,op);assert.ok(await evaluate(`document.querySelector('#rotate-dimensions').textContent.includes('${result.width} × ${result.height}')`))}
await click('#rotate-original');await ready();assert.deepEqual(await pixels(),source)
// Multiple operations in one event turn must compose in their pressed order.
await evaluate(`for(const id of ['right','horizontal','left','vertical'])document.querySelector('#rotate-'+id).click()`);await ready();result=source;for(const op of ['right','horizontal','left','vertical'])result=expected(result,op);assert.deepEqual(await pixels(),result)
for(const index of [1,2,4]){await load(index);await ready();const original=await evaluate('window.fixturePixels['+index+']');assert.deepEqual(await pixels(),original);await click('#rotate-right');await ready();assert.deepEqual(await pixels(),expected(original,'right'))}
const exifOperations=[[],['horizontal'],['half'],['vertical'],['right','horizontal'],['right'],['right','vertical'],['left']];const jpeg=await evaluate('window.fixturePixels[3]')
for(let i=0;i<8;i++){await load(6+i);await ready();let oriented=jpeg;for(const op of exifOperations[i])oriented=expected(oriented,op);assert.deepEqual(await pixels(),oriented,'EXIF '+(i+1));await click('#rotate-right');await ready();assert.deepEqual(await pixels(),expected(oriented,'right'),'EXIF + UI '+(i+1))}
console.log('PASS: asymmetric RGBA pixels; operation order/rapid clicks/identity; transparent PNG and WebP; 8192x1/1x8192; all eight EXIF directions plus displayed-axis rotation')
// Pause actual encoders: an older output must never own a newer operation/file/reset.
await load(0);await ready();await evaluate(`window.nativeToBlob=HTMLCanvasElement.prototype.toBlob;window.encodeQueue=[];HTMLCanvasElement.prototype.toBlob=function(cb,...args){window.nativeToBlob.call(this,b=>window.encodeQueue.push(()=>cb(b)),...args)}`)
await click('#rotate-right');await poll('window.encodeQueue.length===1');assert.equal(await evaluate(`!!document.querySelector('#image-download')`),false);await click('#rotate-horizontal');await evaluate('window.encodeQueue.shift()()');await poll('window.encodeQueue.length===1');await evaluate('window.encodeQueue.shift()()');await ready();assert.deepEqual(await pixels(),expected(expected(source,'right'),'horizontal'))
await click('#rotate-left');await poll('window.encodeQueue.length===1');await load(4);await evaluate('window.encodeQueue.shift()()');await poll('window.encodeQueue.length===1');await evaluate('window.encodeQueue.shift()()');await poll('window.encodeQueue.length===1');await evaluate('window.encodeQueue.shift()()');await ready();assert.deepEqual(await pixels(),await evaluate('window.fixturePixels[4]'));assert.equal(await evaluate(`document.querySelector('.image-source strong').textContent`),'still.webp')
await click('#rotate-right');await poll('window.encodeQueue.length===1');await click('#image-clear');await evaluate('window.encodeQueue.shift()()');await wait(200);assert.equal(await evaluate(`!!document.querySelector('#image-download')||!!document.querySelector('.image-source')`),false);await evaluate('HTMLCanvasElement.prototype.toBlob=window.nativeToBlob')
// A delayed decode is released/closed after file replacement; original orientation resets.
await evaluate(`window.nativeBitmap=createImageBitmap.bind(window);window.delayedDecodes=[];window.createImageBitmap=(...args)=>new Promise(r=>window.delayedDecodes.push(()=>r(window.nativeBitmap(...args))))`);await load(0);await poll('window.delayedDecodes.length===1');for(const id of ['left','right','half','horizontal','vertical','original'])assert.equal(await evaluate(`document.querySelector('#rotate-${id}').disabled`),true);await load(4);await evaluate('window.delayedDecodes.shift()()');await poll('window.delayedDecodes.length===1');await evaluate('window.delayedDecodes.shift()()');await poll('window.delayedDecodes.length===1');await evaluate('window.delayedDecodes.shift()()');await ready();await evaluate('window.createImageBitmap=window.nativeBitmap');assert.deepEqual(await pixels(),await evaluate('window.fixturePixels[4]'))
// Object URL/bitmap/canvas resources, error paths, and clear/unmount.
await evaluate(`window.activeUrls=new Set();window.makeUrl=URL.createObjectURL.bind(URL);window.dropUrl=URL.revokeObjectURL.bind(URL);URL.createObjectURL=b=>{const u=window.makeUrl(b);window.activeUrls.add(u);return u};URL.revokeObjectURL=u=>{window.activeUrls.delete(u);window.dropUrl(u)};window.createElementNative=document.createElement.bind(document);window.allocatedCanvases=[];document.createElement=(tag,...args)=>{const el=window.createElementNative(tag,...args);if(tag==='canvas')window.allocatedCanvases.push(el);return el};window.bitmapOpen=0;window.createImageBitmap=async(...args)=>{const b=await window.nativeBitmap(...args);window.bitmapOpen++;const close=b.close.bind(b);b.close=()=>{window.bitmapOpen--;close()};return b}`);await load(0);await ready();await click('#rotate-left');await ready();assert.equal(await evaluate('window.bitmapOpen'),0);await click('#image-clear');await wait(100);assert.equal(await evaluate('window.activeUrls.size'),0);assert.equal(await evaluate('window.allocatedCanvases.every(c=>c.width===0&&c.height===0)'),true)
await load(0);await ready();await evaluate(`HTMLCanvasElement.prototype.toBlob=function(){throw Error('encode failure')}`);await click('#rotate-right');await poll(`!!document.querySelector('#image-error')`);assert.equal(await evaluate('window.bitmapOpen'),0);assert.equal(await evaluate('window.allocatedCanvases.every(c=>c.width===0&&c.height===0)'),true);assert.equal(await evaluate(`!!document.querySelector('#image-download')`),false);await evaluate('HTMLCanvasElement.prototype.toBlob=window.nativeToBlob');await click('#rotate-left');await ready();await click('#image-clear');await evaluate('document.createElement=window.createElementNative')
await evaluate(`window.createImageBitmap=()=>Promise.reject(Error('decode failure'))`);await load(0);await poll(`!!document.querySelector('#image-error')`);assert.equal(await evaluate(`!!document.querySelector('#image-download')`),false);await evaluate('window.createImageBitmap=window.nativeBitmap')
await evaluate(`const d=new DataTransfer();d.items.add(new File(['broken'],'bad.png',{type:'image/png'}));const e=document.querySelector('#image-files');e.files=d.files;e.dispatchEvent(new Event('change',{bubbles:true}))`);await poll(`!!document.querySelector('#image-error')`)
console.log('PASS: delayed encode/edit/replacement/reset and decode replacement; stale result suppression; bitmap/canvas/object URL cleanup; encode/decode/invalid-file errors; stale unmount')
// Unmount during encoding suppresses output and releases the old route's previews.
await load(0);await ready();await evaluate(`window.pendingUnmountEncode=null;HTMLCanvasElement.prototype.toBlob=function(cb,...args){window.nativeToBlob.call(this,b=>window.pendingUnmountEncode=()=>cb(b),...args)}`);await click('#rotate-right');await poll('!!window.pendingUnmountEncode');await click('.tool-navigation a');await evaluate('window.pendingUnmountEncode();HTMLCanvasElement.prototype.toBlob=window.nativeToBlob');await wait(100);assert.equal(await evaluate('window.activeUrls.size'),0);await click('a[href="/tools/image-rotate"]');assert.equal(await evaluate(`!!document.querySelector('#image-download')||!!document.querySelector('.image-source')`),false)
// Native keyboard and actual download through Edge, then compare the downloaded PNG.
await load(0);await ready();await evaluate(`document.querySelector('#rotate-right').focus()`);await send('Input.dispatchKeyEvent',{type:'keyDown',key:'Enter',code:'Enter',windowsVirtualKeyCode:13,text:'\r'});await send('Input.dispatchKeyEvent',{type:'keyUp',key:'Enter',code:'Enter',windowsVirtualKeyCode:13});await ready();assert.deepEqual(await pixels(),expected(source,'right'))
await send('Input.dispatchKeyEvent',{type:'keyDown',key:'Tab',code:'Tab',windowsVirtualKeyCode:9});await send('Input.dispatchKeyEvent',{type:'keyUp',key:'Tab',code:'Tab',windowsVirtualKeyCode:9});assert.equal(await evaluate('document.activeElement.id'),'rotate-half');await send('Input.dispatchKeyEvent',{type:'keyDown',key:' ',code:'Space',windowsVirtualKeyCode:32,text:' '});await send('Input.dispatchKeyEvent',{type:'keyUp',key:' ',code:'Space',windowsVirtualKeyCode:32});await ready();let downloadedExpected=expected(expected(source,'right'),'half');assert.deepEqual(await pixels(),downloadedExpected)
const downloadName=await evaluate(`document.querySelector('#image-download').download`);const downloadDir=path.resolve(root,'rotation-download');await fs.mkdir(downloadDir,{recursive:true});const downloadPath=path.join(downloadDir,downloadName);try{await fs.unlink(downloadPath)}catch(e){if(e.code!=='ENOENT')throw e}
const browserInfo=await(await fetch('http://127.0.0.1:9222/json/version')).json();const downloads=new WebSocket(browserInfo.webSocketDebuggerUrl);let downloadState='waiting';await new Promise(r=>downloads.addEventListener('open',r,{once:true}));const configured=new Promise((resolve,reject)=>downloads.addEventListener('message',e=>{const m=JSON.parse(e.data);if(m.id===1){if(m.error)reject(m.error);else resolve()}if(m.method==='Browser.downloadProgress')downloadState=m.params.state}));downloads.send(JSON.stringify({id:1,method:'Browser.setDownloadBehavior',params:{behavior:'allow',downloadPath:downloadDir,eventsEnabled:true}}));await configured;
await evaluate(`document.querySelector('#image-download').focus()`);await send('Input.dispatchKeyEvent',{type:'keyDown',key:'Enter',code:'Enter',windowsVirtualKeyCode:13,text:'\r'});await send('Input.dispatchKeyEvent',{type:'keyUp',key:'Enter',code:'Enter',windowsVirtualKeyCode:13});for(let i=0;i<200&&downloadState!=='completed'&&downloadState!=='canceled';i++)await wait(50);downloads.close();assert.equal(downloadState,'completed','Edge download completed');const bytes=await fs.readFile(downloadPath);assert.equal(bytes.subarray(1,4).toString(),'PNG');const actual=await evaluate(`window.readFixture(new Blob([Uint8Array.from(atob(${JSON.stringify(bytes.toString('base64'))}),c=>c.charCodeAt(0))],{type:'image/png'}))`);assert.deepEqual(actual,downloadedExpected)
// Light/dark desktop/mobile preview: displayed pixels and downloaded blob agree.
for(const theme of ['light','dark'])for(const width of [1280,320]){await viewport(width);await click(theme==='light'?'.theme-option:first-child':'.theme-option:last-child');await load(5);await ready();await click('#rotate-right');await ready();await assertNoOverflow();if(width===320){await evaluate(`document.querySelector('#rotate-help').scrollIntoView({block:'center',behavior:'instant'})`);await screenshot(root+'rotation-'+theme+'-320-controls.png')}await evaluate(`document.querySelector('.image-result').scrollIntoView({block:'center',behavior:'instant'})`);await screenshot(root+'rotation-'+theme+'-'+width+'.png');const preview=await evaluate(`(()=>{const e=document.querySelector('.image-preview-grid img');const c=document.createElement('canvas');c.width=e.naturalWidth;c.height=e.naturalHeight;const x=c.getContext('2d');x.drawImage(e,0,0);const r={width:c.width,height:c.height,data:[...x.getImageData(0,0,c.width,c.height).data]};c.width=0;c.height=0;return r})()`);assert.deepEqual(preview,await pixels());assert.equal(await evaluate(`document.querySelector('.tool-panel [role="status"]').getAttribute('aria-live')`),'polite')}
if(await evaluate(`document.querySelector('.detail-favorite').getAttribute('aria-pressed')`)!=='true')await click('.detail-favorite');assert.equal(await evaluate(`JSON.parse(localStorage.getItem('poketsuru-tool-shelf-v1')).recent[0]`),'image-rotate');assert.equal(await evaluate(`JSON.stringify(localStorage).includes('private-asymmetric')||location.search!==''`),false);await click('.tool-navigation a');await click('a[href="/tools/image-rotate"]');assert.equal(await evaluate(`!!document.querySelector('.image-source')`),false);assert.equal(await evaluate(`document.querySelector('.detail-favorite').getAttribute('aria-pressed')`),'true')
finish();console.log('PASS: native Enter/Tab/Space; actual Edge PNG download pixel equality; preview/output equality; light/dark1280/320; live status; ID-only shelf and input privacy; empty re-entry')
