import assert from 'node:assert/strict'
import test from 'node:test'
import {readFileSync} from 'node:fs'
import {tools} from '../src/tools/registry.ts'
import {changeOrientation,originalOrientation,rotationPlan} from '../src/tools/image-rotate/rotation.ts'
const ops=['left','right','half','horizontal','vertical']
const transformGrid=(grid,op)=>{const h=grid.length,w=grid[0].length;if(op==='horizontal')return grid.map(row=>[...row].reverse());if(op==='vertical')return [...grid].reverse().map(row=>[...row]);if(op==='half')return [...grid].reverse().map(row=>[...row].reverse());return Array.from({length:w},(_,y)=>Array.from({length:h},(_,x)=>op==='right'?grid[h-1-x][y]:grid[x][w-1-y]))}
function raster(grid,orientation){const h=grid.length,w=grid[0].length,{size,transform:t}=rotationPlan({width:w,height:h},orientation);const result=Array.from({length:size.height},()=>Array(size.width).fill(null));for(let y=0;y<h;y++)for(let x=0;x<w;x++){const ox=Math.floor(t.a*(x+.5)+t.c*(y+.5)+t.e),oy=Math.floor(t.b*(x+.5)+t.d*(y+.5)+t.f);assert.ok(ox>=0&&ox<size.width&&oy>=0&&oy<size.height);assert.equal(result[oy][ox],null);result[oy][ox]=grid[y][x]}assert.ok(result.every(row=>row.every(x=>x!==null)));return result}
test('画像回転: 90度4回・180度2回・各反転2回で原像、順序は表示方向を基準',()=>{let o=originalOrientation();for(let i=0;i<4;i++)o=changeOrientation(o,'right');assert.deepEqual(o,originalOrientation());for(const op of ['left','half','horizontal','vertical']){o=originalOrientation();for(let i=0;i<(op==='left'?4:2);i++)o=changeOrientation(o,op);assert.deepEqual(o,originalOrientation())}const grid=[[1,2,3],[4,5,6]];let rf=changeOrientation(changeOrientation(originalOrientation(),'right'),'horizontal'),fr=changeOrientation(changeOrientation(originalOrientation(),'horizontal'),'right');assert.deepEqual(raster(grid,rf),[[1,4],[2,5],[3,6]]);assert.notDeepEqual(raster(grid,rf),raster(grid,fr))})
test('画像回転: 19531操作列を独立した画素配列の回転・反転と照合',()=>{const original=[[1,2,3,4],[5,6,7,8],[9,10,11,12]];let count=0;function walk(o,grid,depth){assert.deepEqual(raster(original,o),grid);count++;if(depth)for(const op of ops)walk(changeOrientation(o,op),transformGrid(grid,op),depth-1)}walk(originalOrientation(),original,6);assert.equal(count,19531)})
test('画像回転: 8つの向きで極端比率と上限の寸法・全画素を維持',()=>{const orientations=[originalOrientation(),...ops.map(op=>changeOrientation(originalOrientation(),op)),changeOrientation(changeOrientation(originalOrientation(),'right'),'horizontal'),changeOrientation(changeOrientation(originalOrientation(),'left'),'horizontal')];assert.equal(new Set(orientations.map(o=>JSON.stringify(o))).size,8);for(const size of [{width:8192,height:1},{width:1,height:8192},{width:4000,height:3000}])for(const o of orientations){const plan=rotationPlan(size,o);assert.equal(plan.size.width*plan.size.height,size.width*size.height);assert.ok([size.width,size.height].includes(plan.size.width));assert.ok([size.width,size.height].includes(plan.size.height))}for(const grid of [Array.from({length:1},()=>Array.from({length:31},(_,x)=>x)),Array.from({length:31},(_,y)=>[y])])for(const o of orientations)assert.equal(raster(grid,o).flat().length,31)})
test('画像回転: 無効方向・寸法を拒否し元の設定を変更しない',()=>{const o=Object.freeze(originalOrientation()),size=Object.freeze({width:7,height:3});changeOrientation(o,'right');rotationPlan(size,o);assert.deepEqual(o,originalOrientation());for(const bad of [{a:2,b:0,c:0,d:1},{a:1,b:1,c:0,d:1},{a:1,b:0,c:1,d:0},{a:NaN,b:0,c:0,d:1}])assert.throws(()=>rotationPlan(size,bad));assert.throws(()=>changeOrientation(o,'bad'));for(const bad of [{width:0,height:1},{width:8193,height:1},{width:4000,height:4000}])assert.throws(()=>rotationPlan(bad,o))})
test('画像回転: 遅延ルートと関連・検索登録、画像・名前・向きを保存送信しない',()=>{const tool=tools.find(t=>t.id==='image-rotate');assert.equal(tool.name,'画像の回転・反転');assert.equal(tool.category,'general');assert.deepEqual(tool.relatedTools,['image-resizer','image-joiner']);const app=readFileSync(new URL('../src/App.tsx',import.meta.url),'utf8');assert.ok(app.includes("lazy(() => import('./tools/image-rotate/ImageRotate'))"));assert.ok(app.includes('<Route path="/tools/image-rotate" element={<ImageRotate />} />'));const source=readFileSync(new URL('../src/tools/image-rotate/ImageRotate.tsx',import.meta.url),'utf8');assert.ok(!/fetch\s*\(|localStorage|sessionStorage|URLSearchParams|sendBeacon|dangerouslySetInnerHTML/.test(source));assert.ok(source.includes('useImageWork')&&source.includes('renderImages'))})
