import assert from 'node:assert/strict'
import { pathToFileURL } from 'node:url'
import { navigate, evaluate, send, click, wait, viewport, assertNoOverflow, screenshot, requests, finish } from './browser-client.mjs'
const text=selector=>evaluate('document.querySelector('+JSON.stringify(selector)+').textContent')
const elapsed=async()=>{const value=await text('#stopwatch-time'),parts=value.split(':');return Number(parts[0])*3600+Number(parts[1])*60+Number(parts[2])}
const key=async(key,code,text)=>{await send('Input.dispatchKeyEvent',{type:'keyDown',key,code:key,windowsVirtualKeyCode:code,...(text?{text}:{})});await send('Input.dispatchKeyEvent',{type:'keyUp',key,code:key,windowsVirtualKeyCode:code});await wait(100)}
export async function checkStopwatch(){
 await send('Emulation.setFocusEmulationEnabled',{enabled:true});await send('Page.bringToFront');await send('Browser.grantPermissions',{origin:process.env.TEST_BASE_URL||'http://127.0.0.1:5173',permissions:['clipboardReadWrite','clipboardSanitizedWrite']})
 for(const theme of ['light','dark'])for(const width of [1280,320]){
  await navigate('/tools/stopwatch');await viewport(width);await click(theme==='light'?'.theme-option:first-child':'.theme-option:last-child')
  assert.equal(await text('#stopwatch-time'),'00:00:00.00');assert.equal(await evaluate('document.querySelector("#stopwatch-lap").disabled'),true);assert.equal(await evaluate('document.querySelector("#stopwatch-time").getAttribute("aria-live")'),'off')
  await evaluate('document.querySelector("#stopwatch-start").focus()');await key('Enter',13,'\r');assert.equal(await text('#stopwatch-state'),'計測中');await key('Tab',9);assert.equal(await evaluate('document.activeElement.id'),'stopwatch-lap');await key(' ',32,' ');assert.equal(await evaluate('document.querySelectorAll("#stopwatch-laps li").length'),1);await wait(300);await click('#stopwatch-lap');await click('#stopwatch-start');const paused=await text('#stopwatch-time');await wait(300);assert.equal(await text('#stopwatch-time'),paused);assert.equal(await text('#stopwatch-start'),'再開');await click('#stopwatch-start');await wait(200);await click('#stopwatch-start');assert.ok(await elapsed()>Number(paused.split(':')[2]));
  await click('#stopwatch-copy');const copy=(await evaluate('navigator.clipboard.readText()')).replace(/\r\n?/g,'\n');assert.match(copy,/ストップウォッチ\n合計時間：/);assert.match(copy,/状態：停止中/);assert.match(copy,/ラップ 2：区間/);assert.equal(await evaluate('document.querySelector("#stopwatch-copy-text").value'),copy);assert.match(await text('#stopwatch-notice'),/コピーしました/)
  await assertNoOverflow();if(process.env.TEST_SCREENSHOT_DIR){await evaluate('document.querySelector(".tool-panel").scrollIntoView({block:"start",behavior:"instant"})');await screenshot(process.env.TEST_SCREENSHOT_DIR+'/stopwatch-'+theme+'-'+width+'.png')}
  await click('#stopwatch-reset');assert.equal(await text('#stopwatch-time'),'00:00:00.00');assert.equal(await evaluate('document.querySelectorAll("#stopwatch-laps li").length'),0);assert.equal(await evaluate('document.activeElement.id'),'stopwatch-start');assert.equal(await evaluate('getComputedStyle(document.querySelector("#stopwatch-start")).outlineStyle'),'solid');assert.ok(await evaluate('[...document.querySelectorAll(".action-row button")].every(el=>el.getBoundingClientRect().height>=44)'));assert.equal(await evaluate('!!document.querySelector("#stopwatch-copy-text")'),false)
 }
 await navigate('/tools/stopwatch');await viewport(320);await click('#stopwatch-start');await evaluate('for(let i=0;i<105;i++)document.querySelector("#stopwatch-lap").click()');await wait(150);assert.equal(await evaluate('document.querySelectorAll("#stopwatch-laps li").length'),100);assert.equal(await evaluate('document.querySelector("#stopwatch-lap").disabled'),true);assert.equal(await text('#stopwatch-state'),'計測中');await assertNoOverflow();await click('#stopwatch-copy');assert.match(await evaluate('navigator.clipboard.readText()'),/ラップ 100：/);await click('#stopwatch-reset')
 // Native background tab activation: actual visibility and elapsed difference, no system clock changes.
 if(process.env.TEST_NATIVE_BACKGROUND!=='0'){
 await send('Emulation.setFocusEmulationEnabled',{enabled:false});const swWindow=await send('Browser.getWindowForTarget');await send('Browser.setWindowBounds',{windowId:swWindow.windowId,bounds:{windowState:'minimized'}});await send('Browser.setWindowBounds',{windowId:swWindow.windowId,bounds:{windowState:'normal'}});await send('Page.bringToFront');await wait(200);assert.equal(await evaluate('document.hidden'),false,'Native foreground tab must be visible');await click('#stopwatch-start');const before=await elapsed();const tabs=await(await fetch('http://127.0.0.1:9222/json')).json();const current=tabs.find(t=>t.url.includes('/tools/stopwatch'));const other=await send('Target.createTarget',{url:'about:blank'});await send('Target.activateTarget',{targetId:other.targetId});await wait(150);assert.equal(await evaluate('document.hidden'),true,'Native background tab must be hidden');await wait(1200);await send('Target.activateTarget',{targetId:current.id});await send('Page.bringToFront');await wait(200);assert.equal(await evaluate('document.hidden'),false);assert.ok((await elapsed())-before>=1.2);await send('Target.closeTarget',{targetId:other.targetId});await send('Emulation.setFocusEmulationEnabled',{enabled:true});await click('#stopwatch-start')
 }else console.log('SKIP: native tab visibility (headless); verify this scenario in a windowed/virtual browser')
 // No constantly changing live notification, and bounded refresh rate.
 await click('#stopwatch-reset');await click('#stopwatch-start');await evaluate('window.swTicks=0;window.swObserver=new MutationObserver(()=>window.swTicks++);window.swObserver.observe(document.querySelector("#stopwatch-time"),{childList:true,subtree:true,characterData:true})');const notice=await text('#stopwatch-notice');await wait(1000);assert.ok(await evaluate('window.swTicks')<=13);assert.equal(await text('#stopwatch-notice'),notice);await evaluate('window.swObserver.disconnect()');await click('#stopwatch-start')
 // Copy failures expose a manual fallback; stale promises cannot notify after reset or leave.
 await evaluate('window.swNativeCopy=navigator.clipboard.writeText.bind(navigator.clipboard);navigator.clipboard.writeText=()=>Promise.reject(new Error("test"))');await click('#stopwatch-copy');assert.match(await text('#stopwatch-notice'),/手動でコピー/);assert.ok(await evaluate('document.querySelector("#stopwatch-copy-text").value.includes("合計時間")'));
 await evaluate('navigator.clipboard.writeText=()=>new Promise(resolve=>window.swResolve=resolve)');await click('#stopwatch-copy');await click('#stopwatch-reset');await evaluate('window.swResolve()');await wait(100);assert.doesNotMatch(await text('#stopwatch-notice'),/コピーしました/);await click('#stopwatch-start');await click('#stopwatch-copy');await click('.calculation-related a[href="/tools/duration-calculator"]');await evaluate('window.swResolve()');await evaluate('history.back()');await wait(400);assert.equal(await text('#stopwatch-time'),'00:00:00.00');assert.equal(await text('#stopwatch-notice'),'');await evaluate('navigator.clipboard.writeText=window.swNativeCopy');await click('#stopwatch-start');await send('Page.reload');await wait(500);assert.equal(await text('#stopwatch-time'),'00:00:00.00');assert.equal(await text('#stopwatch-state'),'開始前')
 // Inject only this tab's monotonic source for long duration/limit UI, without altering the PC clock.
 await evaluate('window.swNativeNow=performance.now.bind(performance);window.swNow=window.swNativeNow();performance.now=()=>window.swNow');await click('#stopwatch-start');await evaluate('window.swNow+=49*3600000+1234');await wait(200);assert.equal(await text('#stopwatch-time'),'49:00:01.23');await click('#stopwatch-lap');await assertNoOverflow();await evaluate('window.swNow+=1000*3600000;document.querySelector("#stopwatch-lap").click()');await wait(200);assert.equal(await text('#stopwatch-time'),'999:59:59.99');assert.equal(await text('#stopwatch-state'),'上限で停止');assert.equal(await evaluate('document.querySelector("#stopwatch-start").disabled'),true);assert.match(await text('#stopwatch-notice'),/上限/);assert.equal(await evaluate('document.querySelectorAll("#stopwatch-laps li").length'),1);await assertNoOverflow();await click('#stopwatch-reset');await evaluate('performance.now=window.swNativeNow');await send('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'reduce'}]});await assertNoOverflow();await send('Emulation.setEmulatedMedia',{features:[]})
 assert.equal(await evaluate('location.search'), '');assert.equal(await evaluate('JSON.stringify(localStorage).includes("ラップ 100")||JSON.stringify(localStorage).includes("合計時間：")'),false);assert.ok(!requests.some(r=>r.body.includes('合計時間：')))
 console.log('PASS: stopwatch '+(process.env.TEST_NATIVE_BACKGROUND==='0'?'':'native background/resume,')+'paused exclusion,100laps,49h/limit,Enter/Tab/Space,actual clipboard/failure/races,SPA leave/reload/reset,light-dark320,reduced-motion,10Hz/no live ticks/privacy')
}
if(process.argv[1]&&import.meta.url===pathToFileURL(process.argv[1]).href){await checkStopwatch();finish()}
