import type { ReactNode } from 'react'
import { imageBytes } from './imageMath'
import type { ImageOutput } from './imageBrowser'
import ImagePreview from './ImagePreview'
import { useBlobUrl } from './useBlobUrl'
export function ImageResult({ output, originalBytes }: { output: ImageOutput; originalBytes: number }) {
  const url = useBlobUrl(output.blob)
  return <section className="image-result" aria-label="出力画像"><div className="image-result-heading"><div><h2>できあがり</h2><p>{output.width} × {output.height} px · {imageBytes(output.blob.size)} · {output.mime.replace('image/', '').toUpperCase()}</p></div>{url && <a id="image-download" className="primary-button" href={url} download={output.name}>画像をダウンロード ↓</a>}</div><p className="image-size-message">{output.blob.size > originalBytes ? `容量は元より${imageBytes(output.blob.size - originalBytes)}増えました。形式や品質を変えると小さくできる場合があります。` : `元の合計容量より${imageBytes(originalBytes - output.blob.size)}小さくなりました。`}</p><div className="image-preview-grid"><ImagePreview blob={output.blob} alt="書き出した画像のプレビュー" /></div><p className="image-filename">保存名：{output.name}</p></section>
}
export default function ImageToolShell({ title, description, children, busy, loading, error, output, originalBytes, join = false }: { title: string; description: string; children: ReactNode; busy: boolean; loading: boolean; error: string; output: ImageOutput | null; originalBytes: number; join?: boolean }) {
  return <div className="container tool-page local-image-tool"><header className="tool-header"><h1>{title}</h1><p>{description}</p></header><section className="tool-panel"><div role="status" aria-live="polite">{loading ? <p>画像を確認・読み込んでいます。読み込みが終わるまで設定は変更できません。</p> : busy ? <p>画像を確認・処理しています…</p> : output ? <p>画像ができました。プレビューを確認して保存してください。</p> : null}</div>{children}{error && <p className="error-box" role="alert">{error}</p>}</section>{output && <ImageResult output={output} originalBytes={originalBytes} />}<section className="tool-info"><h2>使い方と対応範囲</h2><p>静止JPG・PNG・WebPに対応します。GIF・HEIC・SVGやアニメーションは使えません。APNGの制御チャンクとWebPのアニメーション指定を検査し、検出した場合は処理しません。形式表示と内容が一致しない画像や破損した画像も受け付けません。</p><p>入力は1枚8 MiB・各辺8192 px・1200万画素以内。{join ? '2〜6枚、入力合計24 MiB・2000万画素以内です。' : '1枚だけ選んでください。'}出力は各辺8192 px・1200万画素・16 MiB以内です。上限以内でも、ブラウザや端末のメモリによって処理できない場合があります。</p><p>縦横比を維持します。極端に細い画像は最低1 pxへの丸めで比率に誤差が出る場合があります。画像の向きはブラウザのEXIF対応で反映します。色・画質・メタデータは元と完全には一致しない場合があります。すべてのメタデータが除去されることは保証しません。</p><p>画像とファイル名・設定は、この画面内だけで扱います。サーバーや解析へ送信せず、保存・URLへの埋め込みもしません。ダウンロードした画像だけを、自分の端末に保存できます。画面を離れると選択と結果は消えます。</p></section></div>
}
