import { useRef, useState } from 'react'
import ImageToolShell from '../local-image/ImageToolShell'
import ImagePreview from '../local-image/ImagePreview'
import { useImageWork } from '../local-image/useImageWork'
import { renderImages } from '../local-image/imageBrowser'
import { imageBytes, joinDimensions, pixelInteger } from '../local-image/imageMath'
export default function ImageJoiner() {
  const work = useImageWork()
  const input = useRef<HTMLInputElement>(null)
  const [direction, setDirection] = useState<'horizontal' | 'vertical'>('horizontal')
  const [cross, setCross] = useState('800'); const [gap, setGap] = useState('16')
  const [background, setBackground] = useState<'transparent' | 'white' | 'black'>('white')
  const total = work.images.reduce((sum, image) => sum + image.file.size, 0)
  return <ImageToolShell title="画像を並べる" description="2〜6枚を、横にも縦にも。ちいさな写真のまとめ作りに。" busy={work.busy} loading={work.loading} error={work.error} output={work.output} originalBytes={total} join>
    <label className="field-label image-file-label" htmlFor="image-files">画像を2〜6枚まとめて選ぶ<span>JPG / PNG / 静止WebP · 1枚8 MiB・合計24 MiBまで</span></label><input aria-describedby={work.error ? 'image-error' : undefined} ref={input} id="image-files" type="file" multiple accept="image/jpeg,image/png,image/webp" onClick={e => { e.currentTarget.value = '' }} onChange={e => { const files = Array.from(e.target.files ?? []); if (files.length) void work.load(files, 2, 6) }} />
    {work.images.length > 0 && <ol className="image-order-list">{work.images.map((image, index) => <li key={index}><ImagePreview blob={image.thumbnail} alt={`画像${index + 1}の縮小プレビュー`} /><div><strong>{index + 1}. {image.file.name}</strong><p>{image.width} × {image.height} px · {imageBytes(image.file.size)}</p><div className="image-order-buttons"><button type="button" className="secondary-button" disabled={index === 0 || work.busy} aria-label={`画像${index + 1}を前へ移動`} onClick={() => work.reorder(index, index - 1)}>← 前へ</button><button type="button" className="secondary-button" disabled={index === work.images.length - 1 || work.busy} aria-label={`画像${index + 1}を後ろへ移動`} onClick={() => work.reorder(index, index + 1)}>後ろへ →</button></div></div></li>)}</ol>}
    <div className="image-settings everyday-columns"><label className="field-label" htmlFor="image-direction">並べる方向<select aria-describedby={work.error ? 'image-error' : undefined} id="image-direction" disabled={work.loading} value={direction} onChange={e => { setDirection(e.target.value as typeof direction); work.resetResult() }}><option value="horizontal">横に並べる</option><option value="vertical">縦に並べる</option></select></label><label className="field-label" htmlFor="image-cross">{direction === 'horizontal' ? 'そろえる高さ' : 'そろえる幅'}の上限（px）<input aria-describedby={work.error ? 'image-error' : undefined} id="image-cross" disabled={work.loading} type="text" inputMode="numeric" value={cross} onChange={e => { setCross(e.target.value); work.resetResult() }} /></label><label className="field-label" htmlFor="image-gap">画像の間の余白（0〜200 px）<input aria-describedby={work.error ? 'image-error' : undefined} id="image-gap" disabled={work.loading} type="text" inputMode="numeric" value={gap} onChange={e => { setGap(e.target.value); work.resetResult() }} /></label><label className="field-label" htmlFor="image-background">背景<select aria-describedby={work.error ? 'image-error' : undefined} id="image-background" disabled={work.loading} value={background} onChange={e => { setBackground(e.target.value as typeof background); work.resetResult() }}><option value="white">白</option><option value="transparent">透過</option><option value="black">黒</option></select></label></div>
    <p className="image-hint">縦横比を維持し、横並びでは高さ、縦並びでは幅をそろえます。小さな画像は拡大せず、指定した上限より小さくなる場合があります。出力は透過に対応したPNGです。出力が上限を超える場合は、そろえる辺や余白を小さくしてください。</p>
    <div className="action-row"><button id="image-process" type="button" className="primary-button" disabled={work.images.length < 2 || work.busy} onClick={() => void work.run(isCurrent => { const plan = joinDimensions(work.images, direction, pixelInteger(cross, 1, 4096), pixelInteger(gap, 0, 200)); return renderImages(work.images, plan.placements, plan.size, 'image/png', 1, background, isCurrent) })}>並べて1枚にする</button><button id="image-clear" type="button" className="secondary-button" onClick={() => { work.clear(); if (input.current) input.current.value = '' }}>画像を消去・中断</button></div>
  </ImageToolShell>
}
