import type { Tool } from '../types/tool'

export const tools: Tool[] = [
  { id: 'holiday-style', name: '休日スタイル診断', description: '今の気分を5つ選んで、今日の過ごし方を楽しむ遊び。', category: 'general', keywords: ['休日', '気分', '診断', '遊び', '過ごし方', 'holiday', 'quiz'], path: '/tools/holiday-style', relatedTools: ['pocket-companion'] },
  { id: 'pocket-companion', name: 'ポケット相棒診断', description: '空想の旅の5つの選択から、小さな道具の相棒を探す遊び。', category: 'general', keywords: ['相棒', 'ポケット', '診断', '物語', '遊び', 'companion', 'quiz'], path: '/tools/pocket-companion', relatedTools: ['holiday-style'] },
  { id: 'unit-converter', name: '単位変換', description: '長さ・重量・体積・面積・温度を固定換算します。', category: 'general', keywords: ['単位', '長さ', '重量', '体積', '面積', '温度', 'インチ', 'unit', 'convert'], path: '/tools/unit-converter', relatedTools: ['percentage-calculator'] },
  { id: 'bill-splitter', name: '割り勘計算', description: '正確な配分や同額の集金と余りを計算します。', category: 'general', keywords: ['割り勘', '円', '人数', '集金', '会計', 'bill', 'split'], path: '/tools/bill-splitter', relatedTools: ['percentage-calculator'] },
  { id: 'roulette-picker', name: 'ルーレット抽選', description: '候補を同じ確率で選び、選択済みを除外できます。', category: 'general', keywords: ['ルーレット', '抽選', 'くじ', 'ランダム', '選ぶ', 'roulette', 'random'], path: '/tools/roulette-picker' },
  {
    id: 'json-formatter',
    name: 'JSON Formatter',
    description: 'JSONを整形・圧縮します。',
    category: 'developer',
    keywords: ['json', 'format', 'formatter', '整形', '圧縮'],
    path: '/tools/json-formatter',
    relatedTools: ['sql-in-generator'],
  },
  {
    id: 'sql-in-generator',
    name: 'SQL IN Generator',
    description: '値の一覧からSQLのIN句を生成します。',
    category: 'developer',
    keywords: ['sql', 'in', 'generator', 'in句', 'sql生成', 'リスト'],
    path: '/tools/sql-in-generator',
    relatedTools: ['json-formatter'],
  },
  {
    id: 'timestamp-converter',
    name: 'Timestamp Converter',
    description: 'Unix Timestampと日時を相互変換します。',
    category: 'developer',
    keywords: ['timestamp', 'unix', 'epoch', '日時', '時刻', '変換'],
    path: '/tools/timestamp-converter',
  },
  {
    id: 'character-counter',
    name: '文字数カウンター',
    description: '入力したテキストの文字数・行数・単語数・バイト数をリアルタイムで確認します。',
    category: 'text',
    keywords: ['文字数', '文字数カウント', 'カウンター', '行数', '単語数', 'バイト数', 'character', 'count', 'text'],
    path: '/tools/character-counter',
  },
  {
    id: 'url-encode-decode',
    name: 'URL Encode / Decode',
    description: '文字列やURLをURLエンコード・デコードします。',
    category: 'developer',
    keywords: ['url', 'encode', 'decode', 'percent', 'encoding', 'URLエンコード', 'URLデコード', 'パーセントエンコード'],
    path: '/tools/url-encode-decode',
    relatedTools: ['base64-encode-decode'],
  },
  {
    id: 'base64-encode-decode',
    name: 'Base64 Encode / Decode',
    description: 'テキストをBase64へエンコード・デコードします。',
    category: 'developer',
    keywords: ['base64', 'encode', 'decode', 'encoding', 'Base64エンコード', 'Base64デコード', '変換'],
    path: '/tools/base64-encode-decode',
    relatedTools: ['url-encode-decode'],
  },
  {
    id: 'uuid-generator',
    name: 'UUID Generator',
    description: 'UUID v4をブラウザ上で生成します。',
    category: 'developer',
    keywords: ['uuid', 'guid', 'uuid v4', 'generator', 'random', 'UUID生成', 'GUID生成'],
    path: '/tools/uuid-generator',
  },
  {
    id: 'date-calculator',
    name: '日付・日数計算',
    description: '2つの日付の間の日数や、指定した日付から○日後・○日前の日付を計算します。',
    category: 'datetime',
    keywords: ['日付', '日数', '日数計算', '何日後', '何日前', '期間', 'date', 'days', 'calculator'],
    path: '/tools/date-calculator',
    relatedTools: ['japanese-era-converter'],
  },
  {
    id: 'japanese-era-converter',
    name: '西暦・和暦変換',
    description: '西暦と和暦を相互変換します。',
    category: 'general',
    keywords: ['西暦', '和暦', '令和', '平成', '昭和', '大正', '明治', '変換', '元号', 'wareki', 'era'],
    path: '/tools/japanese-era-converter',
    relatedTools: ['date-calculator'],
  },
  {
    id: 'qr-code-generator',
    name: 'QRコード生成',
    description: 'URLやテキストからQRコードを生成します。',
    category: 'general',
    keywords: ['qr', 'qr code', 'QRコード', 'QR生成', 'URL', 'テキスト', '二次元コード', 'generator'],
    path: '/tools/qr-code-generator',
  },
  {
    id: 'text-diff',
    name: 'Text Diff',
    description: '2つのテキストの差分を確認します。',
    category: 'text',
    keywords: ['diff', 'difference', 'text diff', 'テキスト差分', '差分', '比較', 'diff checker'],
    path: '/tools/text-diff',
    relatedTools: ['character-counter'],
  },
  {
    id: 'ipv4-cidr',
    name: 'IPv4 CIDR計算',
    description: 'IPv4のネットワーク、マスク、アドレス範囲・ホスト数を計算します。',
    category: 'network',
    keywords: ['ipv4', 'cidr', 'subnet', 'network', 'IPアドレス', 'サブネットマスク', 'ネットワーク', 'ホスト'],
    path: '/tools/ipv4-cidr',
  },
  {
    id: 'sha256',
    name: 'SHA-256ハッシュ計算',
    description: 'テキスト・ファイルのSHA-256を生成し、期待値と照合します。',
    category: 'developer',
    keywords: ['sha256', 'sha-256', 'hash', 'checksum', 'ハッシュ', 'チェックサム', '照合', 'ファイル'],
    path: '/tools/sha256',
  },
  {
    id: 'radix-converter',
    name: '進数変換',
    description: '整数を2・8・10・16進数へ精度を維持して相互変換します。',
    category: 'developer',
    keywords: ['radix', 'binary', 'octal', 'decimal', 'hex', 'bigint', '進数', '2進数', '8進数', '10進数', '16進数'],
    path: '/tools/radix-converter',
  },
  {
    id: 'html-escape',
    name: 'HTMLエスケープ・解除',
    description: 'HTMLの基本5文字と対応する文字参照を変換します。',
    category: 'text',
    keywords: ['html', 'escape', 'unescape', 'entity', 'エスケープ', '解除', '文字参照', '引用符'],
    path: '/tools/html-escape',
  },
  {
    id: 'percentage-calculator',
    name: '割合・増減率計算',
    description: '割合、指定割合の値、変更前後の増減率を計算します。',
    category: 'general',
    keywords: ['percentage', 'percent', 'ratio', '割合', '増減率', 'パーセント', '割引', '売上'],
    path: '/tools/percentage-calculator',
  },
]
