import type { Tool } from '../types/tool'

export const tools: Tool[] = [
  {
    id: 'json-formatter',
    name: 'JSON Formatter',
    description: 'JSONを整形・圧縮します。',
    category: 'developer',
    keywords: ['json', 'format', 'formatter', '整形', '圧縮'],
    path: '/tools/json-formatter',
    relatedTools: ['sql-in-generator'],
  },
  {
    id: 'sql-in-generator',
    name: 'SQL IN Generator',
    description: '値の一覧からSQLのIN句を生成します。',
    category: 'developer',
    keywords: ['sql', 'in', 'generator', 'in句', 'sql生成', 'リスト'],
    path: '/tools/sql-in-generator',
    relatedTools: ['json-formatter'],
  },
  {
    id: 'timestamp-converter',
    name: 'Timestamp Converter',
    description: 'Unix Timestampと日時を相互変換します。',
    category: 'developer',
    keywords: ['timestamp', 'unix', 'epoch', '日時', '時刻', '変換'],
    path: '/tools/timestamp-converter',
  },
  {
    id: 'character-counter',
    name: '文字数カウンター',
    description: '入力したテキストの文字数・行数・単語数・バイト数をリアルタイムで確認します。',
    category: 'text',
    keywords: ['文字数', '文字数カウント', 'カウンター', '行数', '単語数', 'バイト数', 'character', 'count', 'text'],
    path: '/tools/character-counter',
  },
  {
    id: 'url-encode-decode',
    name: 'URL Encode / Decode',
    description: '文字列やURLをURLエンコード・デコードします。',
    category: 'developer',
    keywords: ['url', 'encode', 'decode', 'percent', 'encoding', 'URLエンコード', 'URLデコード', 'パーセントエンコード'],
    path: '/tools/url-encode-decode',
    relatedTools: ['base64-encode-decode'],
  },
  {
    id: 'base64-encode-decode',
    name: 'Base64 Encode / Decode',
    description: 'テキストをBase64へエンコード・デコードします。',
    category: 'developer',
    keywords: ['base64', 'encode', 'decode', 'encoding', 'Base64エンコード', 'Base64デコード', '変換'],
    path: '/tools/base64-encode-decode',
    relatedTools: ['url-encode-decode'],
  },
]
