import type { Tool } from '../types/tool'

export const tools: Tool[] = [
  { id: 'fraction-calculator', name: '分数計算', description: '2つの分数を足す・引く・掛ける・割る。約分した答えを正確に求めます。', category: 'general', keywords: ['分数', '約分', '帯分数', '通分', '分子', '分母', '足し算', '引き算', '掛け算', '割り算', '算数', '学習', 'ぶんすう', 'fraction', 'calculator'], path: '/tools/fraction-calculator', relatedTools: ['percentage-calculator', 'aspect-ratio'] },
  { id: 'color-converter', name: 'カラーコード変換', description: 'HEX・RGB・HSLを相互変換し、色見本を確認できます。', category: 'general', keywords: ['カラーコード', 'カラー', '色', '色変換', '色見本', 'hex', 'rgb', 'hsl', 'color', 'colour', 'convert', '16進数'], path: '/tools/color-converter' },
  { id: 'age-calculator', name: '経過年月・年齢計算', description: '誕生日や記念日から、基準日までの年・月・日と総日数を計算します。', category: 'datetime', keywords: ['日付・時間', '年齢', '経過', '年月', '何歳', '誕生日', '記念日', '満年齢', '期間', 'age', 'elapsed', 'birthday'], path: '/tools/age-calculator', relatedTools: ['date-calculator'] },
  { id: 'sequence-generator', name: '連番作成', description: '開始番号・件数・増分を指定して、番号やラベルを1行ずつ作ります。', category: 'general', keywords: ['連番', '番号', '一覧', '受付番号', 'ファイル名', 'ラベル', 'ゼロ埋め', '増分', 'sequence', 'number', 'serial', 'リスト'], path: '/tools/sequence-generator', relatedTools: ['text-formatter', 'sql-in-generator'] },
  {
    id: 'image-crop',
    name: '画像の切り抜き',
    description: '写真の必要な範囲を、自由な矩形や固定比率で切り抜いてPNG保存します。',
    category: 'general',
    keywords: ['画像', '写真', '切り抜き', 'トリミング', 'クロップ', '正方形', 'crop', 'trim', '1:1', '4:3', '16:9'],
    path: '/tools/image-crop',
    relatedTools: ['image-resizer', 'image-rotate', 'image-joiner'],
  },
  { id: 'countdown-timer', name: 'カウントダウンタイマー', description: '1秒〜24時間の残り時間を、音なしで画面に表示します。', category: 'general', keywords: ['日付・時間', 'カウントダウン', 'タイマー', '残り時間', '時間', '分', '秒', '作業', 'countdown', 'timer', '残り時間を計る'], path: '/tools/countdown-timer', relatedTools: ['stopwatch', 'duration-calculator'] },
  { id: 'stopwatch', name: 'ストップウォッチ', description: '経過時間を計り、最大100件のラップと区間時間を記録します。', category: 'general', keywords: ['日付・時間', 'ストップウォッチ', '時間', '経過時間', 'ラップ', '計測', '勉強', '作業', '運動', 'stopwatch', 'lap', '時間を計る'], path: '/tools/stopwatch', relatedTools: ['duration-calculator', 'date-calculator'] },
  { id: 'width-converter', name: '英数字の全角・半角変換', description: '英字・数字・記号・スペースを選んで、全角と半角を変換します。', category: 'text', keywords: ['全角', '半角', '英字', '数字', '英数字', '記号', 'スペース', '文書', 'フォーム', 'width', 'zenkaku', 'hankaku', '英数字を揃える'], path: '/tools/width-converter', relatedTools: ['text-formatter', 'text-replace', 'character-counter'] },
  { id: 'aspect-ratio', name: '縦横比・サイズ計算', description: '幅と高さの比率を約分し、同じ比率の新しい寸法を計算します。', category: 'general', keywords: ['縦横比', '比率', 'サイズ', '幅', '高さ', '寸法', '画像', '動画', '印刷', 'aspect ratio', 'ratio', '16:9', '画像なしでサイズ計算'], path: '/tools/aspect-ratio', relatedTools: ['image-resizer', 'unit-converter', 'percentage-calculator'] },
  { id: 'text-replace', name: '文字列の一括置換', description: '本文中の文字列を完全一致でまとめて置換・削除します。', category: 'text', keywords: ['文字列', '一括置換', '置換', '置き換え', '検索', '削除', '文章', '文書', 'replace', 'find', '文字を置き換える'], path: '/tools/text-replace', relatedTools: ['text-formatter', 'character-counter', 'text-diff'] },
  { id: 'image-rotate', name: '画像の回転・反転', description: '写真を90度ずつ回転、または左右・上下に反転してPNGで保存します。', category: 'general', keywords: ['画像', '写真', '回転', '反転', '向き', '左右', '上下', 'rotate', 'flip', 'mirror', '写真の向き', '鏡像'], path: '/tools/image-rotate', relatedTools: ['image-resizer', 'image-joiner'] },
  { id: 'random-grouping', name: 'ランダム組み分け', description: 'イベントやゲームの候補全員を、人数差1以内の組に分けます。', category: 'general', keywords: ['組み分け', 'グループ分け', 'チーム分け', '班分け', 'ランダム', '抽選', 'イベント', 'ゲーム', 'random', 'group', 'team'], path: '/tools/random-grouping', relatedTools: ['roulette-picker'] },
  { id: 'duration-calculator', name: '時間の足し算・引き算', description: '動画や作業の時間を足し引きし、合計時間・分・秒を計算します。', category: 'general', keywords: ['日付・時間', '時間', '足し算', '引き算', '時間計算', '動画時間', '作業時間', 'duration', 'hours', 'minutes', 'seconds'], path: '/tools/duration-calculator', relatedTools: ['date-calculator', 'timestamp-converter', 'unit-converter'] },
  { id: 'text-formatter', name: 'テキスト整形', description: '文章や一覧の空白・空行・重複を、選んだ操作だけで整えます。', category: 'text', keywords: ['テキスト', '文章', '整形', '空白', '空行', '重複', '改行', '削除', 'trim', 'format', 'dedupe', '空白を消す', '行をまとめる', '文章整理'], path: '/tools/text-formatter', relatedTools: ['character-counter', 'text-diff', 'html-escape'] },
  { id: 'unit-price-comparison', name: '買い物の単価比較', description: '2〜4商品の価格を100g・100mL・1個など同じ量で比べます。', category: 'general', keywords: ['単価', '買い物', '価格', '比較', '安い', 'お得', '送料', '100g', '100mL', '個数', 'unit price', 'price comparison', 'どっちが安い', '値段'], path: '/tools/unit-price-comparison', relatedTools: ['bill-splitter', 'unit-converter', 'recipe-scaler'] },
  { id: 'recipe-scaler', name: 'レシピの分量調整', description: '人数や倍率に合わせて、材料の量をまとめて調整します。', category: 'general', keywords: ['レシピ', '料理', '材料', '分量', '人数', '倍率', '半分', '倍量', 'recipe', 'scale', '何人分', 'お菓子', 'りょうり'], path: '/tools/recipe-scaler', relatedTools: ['unit-price-comparison', 'unit-converter', 'percentage-calculator'] },
  { id: 'image-resizer', name: '画像サイズ変更・圧縮', description: 'ローカル画像の縦横比を保ち、サイズ・形式・品質を変えます。', category: 'general', keywords: ['画像', '写真', '圧縮', 'サイズ', '縮小', 'JPEG', 'PNG', 'WebP', 'image', 'resize', "リサイズ", "画像を小さく", "写真を小さく"], path: '/tools/image-resizer', relatedTools: ['image-joiner'] },
  { id: 'image-joiner', name: '画像を並べる', description: '2〜6枚のローカル画像を横・縦に並べて1枚にします。', category: 'general', keywords: ['画像', '写真', '結合', '並べる', '横', '縦', 'image', 'join', "写真をまとめる", "連結"], path: '/tools/image-joiner', relatedTools: ['image-resizer'] },
  { id: 'holiday-style', name: '休日スタイル診断', description: '今の気分を5つ選んで、今日の過ごし方を楽しむ遊び。', category: 'general', keywords: ['休日', '気分', '診断', '遊び', '過ごし方', 'holiday', 'quiz', "休みの日", "休日の過ごし方"], path: '/tools/holiday-style', relatedTools: ['pocket-companion'] },
  { id: 'pocket-companion', name: '行動スタイル診断', description: '5つの質問で、日常の行動スタイルを振り返ります。', category: 'general', keywords: ['相棒', 'ポケット', '診断', '物語', '遊び', 'companion', 'quiz', '行動', 'スタイル', '計画', '実践', "相棒を選ぶ", "空想"], path: '/tools/pocket-companion', relatedTools: ['holiday-style'] },
  { id: 'unit-converter', name: '単位変換', description: '長さ・重量・体積・面積・温度を固定換算します。', category: 'general', keywords: ['単位', '長さ', '重量', '体積', '面積', '温度', 'インチ', 'unit', 'convert', "重さ", "センチ", "メートル", "リットル", "摂氏", "華氏"], path: '/tools/unit-converter', relatedTools: ['percentage-calculator'] },
  { id: 'bill-splitter', name: '割り勘計算', description: '正確な配分や同額の集金と余りを計算します。', category: 'general', keywords: ['割り勘', '円', '人数', '集金', '会計', 'bill', 'split', "わりかん", "割勘", "会計を分ける"], path: '/tools/bill-splitter', relatedTools: ['percentage-calculator'] },
  { id: 'roulette-picker', name: 'ルーレット抽選', description: '候補を同じ確率で選び、選択済みを除外できます。', category: 'general', keywords: ['ルーレット', '抽選', 'くじ', 'ランダム', '選ぶ', 'roulette', 'random', "くじ引き", "抽せん"], path: '/tools/roulette-picker' },
  {
    id: 'json-formatter',
    name: 'JSON Formatter',
    description: 'JSONを整形・圧縮します。',
    category: 'developer',
    keywords: ['json', 'format', 'formatter', '整形', '圧縮', "ジェイソン", "データ整形"],
    path: '/tools/json-formatter',
    relatedTools: ['sql-in-generator'],
  },
  {
    id: 'sql-in-generator',
    name: 'SQL IN Generator',
    description: '値の一覧からSQLのIN句を生成します。',
    category: 'developer',
    keywords: ['sql', 'in', 'generator', 'in句', 'sql生成', 'リスト', "エスキューエル", "値リスト"],
    path: '/tools/sql-in-generator',
    relatedTools: ['json-formatter'],
  },
  {
    id: 'timestamp-converter',
    name: 'Timestamp Converter',
    description: 'Unix Timestampと日時を相互変換します。',
    category: 'developer',
    keywords: ['日付・時間', 'timestamp', 'unix', 'epoch', '日時', '時刻', '変換', "タイムスタンプ", "UNIX時間"],
    path: '/tools/timestamp-converter',
  },
  {
    id: 'character-counter',
    name: '文字数カウンター',
    description: '入力したテキストの文字数・行数・単語数・バイト数をリアルタイムで確認します。',
    category: 'text',
    keywords: ['文字数', '文字数カウント', 'カウンター', '行数', '単語数', 'バイト数', 'character', 'count', 'text', "文字を数える", "文字カウント"],
    path: '/tools/character-counter',
  },
  {
    id: 'url-encode-decode',
    name: 'URL Encode / Decode',
    description: '文字列やURLをURLエンコード・デコードします。',
    category: 'developer',
    keywords: ['url', 'encode', 'decode', 'percent', 'encoding', 'URLエンコード', 'URLデコード', 'パーセントエンコード', "パーセントエンコード", "URL変換"],
    path: '/tools/url-encode-decode',
    relatedTools: ['base64-encode-decode'],
  },
  {
    id: 'base64-encode-decode',
    name: 'Base64 Encode / Decode',
    description: 'テキストをBase64へエンコード・デコードします。',
    category: 'developer',
    keywords: ['base64', 'encode', 'decode', 'encoding', 'Base64エンコード', 'Base64デコード', '変換', "ベース64", "文字列をBase64"],
    path: '/tools/base64-encode-decode',
    relatedTools: ['url-encode-decode'],
  },
  {
    id: 'uuid-generator',
    name: 'UUID Generator',
    description: 'UUID v4をブラウザ上で生成します。',
    category: 'developer',
    keywords: ['uuid', 'guid', 'uuid v4', 'generator', 'random', 'UUID生成', 'GUID生成', "ユーユーアイディー", "識別子", "ランダムID"],
    path: '/tools/uuid-generator',
  },
  {
    id: 'date-calculator',
    name: '日付・日数計算',
    description: '2つの日付の間の日数や、指定した日付から○日後・○日前の日付を計算します。',
    category: 'datetime',
    keywords: ['日付・時間', '日付', '日数', '日数計算', '何日後', '何日前', '期間', 'date', 'days', 'calculator', "日にち", "日付差", "何日後"],
    path: '/tools/date-calculator',
    relatedTools: ['japanese-era-converter'],
  },
  {
    id: 'japanese-era-converter',
    name: '西暦・和暦変換',
    description: '西暦と和暦を相互変換します。',
    category: 'general',
    keywords: ['日付・時間', '西暦', '和暦', '令和', '平成', '昭和', '大正', '明治', '変換', '元号', 'wareki', 'era', "元号", "れいわ"],
    path: '/tools/japanese-era-converter',
    relatedTools: ['date-calculator'],
  },
  {
    id: 'qr-code-generator',
    name: 'QRコード生成',
    description: 'URLやテキストからQRコードを生成します。',
    category: 'general',
    keywords: ['qr', 'qr code', 'QRコード', 'QR生成', 'URL', 'テキスト', '二次元コード', 'generator', "キューアール", "二次元バーコード"],
    path: '/tools/qr-code-generator',
  },
  {
    id: 'text-diff',
    name: 'Text Diff',
    description: '2つのテキストの差分を確認します。',
    category: 'text',
    keywords: ['diff', 'difference', 'text diff', 'テキスト差分', '差分', '比較', 'diff checker', "違い", "文章比較"],
    path: '/tools/text-diff',
    relatedTools: ['character-counter'],
  },
  {
    id: 'ipv4-cidr',
    name: 'IPv4 CIDR計算',
    description: 'IPv4のネットワーク、マスク、アドレス範囲・ホスト数を計算します。',
    category: 'network',
    keywords: ['ipv4', 'cidr', 'subnet', 'network', 'IPアドレス', 'サブネットマスク', 'ネットワーク', 'ホスト', "サブネット計算", "シーアイディーアール"],
    path: '/tools/ipv4-cidr',
  },
  {
    id: 'sha256',
    name: 'SHA-256ハッシュ計算',
    description: 'テキスト・ファイルのSHA-256を生成し、期待値と照合します。',
    category: 'developer',
    keywords: ['sha256', 'sha-256', 'hash', 'checksum', 'ハッシュ', 'チェックサム', '照合', 'ファイル', "ハッシュ値", "ファイル照合"],
    path: '/tools/sha256',
  },
  {
    id: 'radix-converter',
    name: '進数変換',
    description: '整数を2・8・10・16進数へ精度を維持して相互変換します。',
    category: 'developer',
    keywords: ['radix', 'binary', 'octal', 'decimal', 'hex', 'bigint', '進数', '2進数', '8進数', '10進数', '16進数', "基数", "二進数", "十六進数"],
    path: '/tools/radix-converter',
  },
  {
    id: 'html-escape',
    name: 'HTMLエスケープ・解除',
    description: 'HTMLの基本5文字と対応する文字参照を変換します。',
    category: 'text',
    keywords: ['html', 'escape', 'unescape', 'entity', 'エスケープ', '解除', '文字参照', '引用符', "特殊文字", "タグを文字に"],
    path: '/tools/html-escape',
  },
  {
    id: 'percentage-calculator',
    name: '割合・増減率計算',
    description: '割合、指定割合の値、変更前後の増減率を計算します。',
    category: 'general',
    keywords: ['percentage', 'percent', 'ratio', '割合', '増減率', 'パーセント', '割引', '売上', "百分率", "何パーセント"],
    path: '/tools/percentage-calculator',
  },
]
